README.md
Because we have now the format callback(error, response) we have to update the main readme file
=> update readme with new callback

package.json, src/kuzzle.js, src/kuzzleRoom.js, test/kuzzleDataCollection/methods.test.js
* Now enters a pseudo-offline mode when initializing
* added more unit tests
=> Init offline mode

package.json, src/kuzzle.js, src/kuzzleDataCollection.js, test/kuzzle/constructor.test.js, test/kuzzle/methods.test.js, test/kuzzleDataCollection/methods.test.js
* Added the new ``connect`` option and method, allowing to manually connect to Kuzzle instead of doing it automatically
* Renamed ``KuzzleDataCollection.publish`` into ``KuzzleDataCollection.publishMessage``
* Added the possibility to force a document ID with ``KuzzleDataCollection.createDocument``
=> implemented the latest SDK documentation version

.eslintrc, src/security/kuzzleProfile.js, src/security/kuzzleSecurityDocument.js, src/security/kuzzleUser.js, test/security/kuzzleProfile/methods.test.js
* Fix hydrate user
* Fix hydrate profile
* Add option `replace` in setContent
=> fix hydrate user and replace in setContent

src/kuzzle.js, test/kuzzle/methods.test.js
Now ensure that arguments provided to `Kuzzle.dataCollectionFactory` are all of type "string"
=> fixed issue #76

src/kuzzleDataMapping.js, test/kuzzleDataMapping/methods.test.js
Fixes #95 + added unit tests to catch this kind of bug
=> fix #95: handle empty mappings

src/security/kuzzleUser.js, test/security/kuzzleSecurity/userMethods.test.js, test/security/kuzzleUser/methods.test.js
According to this PR [https://github.com/kuzzleio/kuzzle/pull/378](https://github.com/kuzzleio/kuzzle/pull/378) we have changed `profilesIds` to `profileIds`
=> Replaced `profilesIds` to `profileIds`

deploy.sh
`Gruntfile` does not exist anymore.
=> Remove grunt from build.sh

package.json, src/kuzzle.js, test/kuzzle/methods.test.js
=> Add handling of from and size options in listCollections

src/kuzzleDataCollection.js, test/kuzzleDataCollection/methods.test.js
=> Add aggregations support on advancedSearch

package.json, src/kuzzle.js, test/.eslintrc.json, test/kuzzle/query.test.js
fix #137 
link kuzzleio/kuzzle#532
=> Add refresh as option

src/Collection.js, test/Collection/methods.test.js
fix https://github.com/kuzzleio/sdk/issues/4
=> Wrap filter in query for deleteDocument

package-lock.json, src/MemoryStorage.js, test/MemoryStorage/methods.test.js
fix https://github.com/kuzzleio/kuzzle-sdk/issues/46
=> Rename index parameter into idx in memory storage

package.json
| Kuzzle | Proxy |
|--------|-------|
| 1.0.0 | 1.0.0 |
- [ [#245](https://github.com/kuzzleio/sdk-javascript/pull/245) ] Make collection.create() pass the collection object to the callback   ([xbill82](https://github.com/xbill82))
---
=> Release 5.0.8

package.json
| Kuzzle | Proxy |
|--------|-------|
| 1.0.0 | 1.0.0 |
- [ [#247](https://github.com/kuzzleio/sdk-javascript/pull/247) ] Remove cleanHistory from event loop upon disconnection   ([scottinet](https://github.com/scottinet))
- [ [#245](https://github.com/kuzzleio/sdk-javascript/pull/245) ] Make collection.create() pass the collection object to the callback   ([xbill82](https://github.com/xbill82))
---
=> Release 5.0.9

src/networkWrapper/protocols/abstract/common.js, src/networkWrapper/protocols/http.js, test/network/http.test.js, test/network/query.test.js
Fix an error in `_emitRequest()`
This snippet should not return an error
```
const Kuzzle = require('kuzzle-sdk');
const kuzzle = new Kuzzle('localhost');
kuzzle.connect()
.then(() => kuzzle.index.create('my-index', {}))
.then(result => {
console.log(result)
})
.catch(error => {
console.log(error)
})
```
=> fix http send

src/networkWrapper/protocols/abstract/common.js, src/networkWrapper/protocols/http.js, test/network/http.test.js, test/network/query.test.js
Reverts kuzzleio/sdk-javascript#295
=> Revert "fix http send"

.travis.yml, README.md, deploy.sh, package-lock.json, package.json
- [ [#308](https://github.com/kuzzleio/sdk-javascript/pull/308) ] KZL 174 - Update README for SDK V6   ([Aschen](https://github.com/Aschen))
---
=> Release 6.0.0-beta-1

src/controllers/realtime/index.js, test/controllers/realtime.test.js
Return only a boolean instead of `{ published: <boolean> }`
- rename body argument to be more explicit
=> Fix realtime publish return

README.md, features/steps/document.js, package-lock.json, package.json, src/controllers/document.js, src/protocols/abstract/realtime.js, test/controllers/document.test.js, test/protocol/websocket.test.js, webpack.config.js
- [ [#349](https://github.com/kuzzleio/sdk-javascript/pull/349) ] [build] Update webpack build config to fix raw web usage   ([Njuelle](https://github.com/Njuelle))
- [ [#345](https://github.com/kuzzleio/sdk-javascript/pull/345) ] Fix 343 unhandled rejection on connect   ([Aschen](https://github.com/Aschen))
- [ [#348](https://github.com/kuzzleio/sdk-javascript/pull/348) ] Put document:create optional args in last position   ([Aschen](https://github.com/Aschen))
---
=> Release 6.0.0-beta-4

src/protocols/websocket.js, test/protocol/websocket.test.js
Allow users to pass HTTP headers to new WebSocket instances. This is simply a matter of making accessible the full capabilities of WebSockets, as described by the RFC.
Unfortunately, the browsers' WebSocket interface does not allow HTTP headers, so this feature is only usable when using this SDK with Node.js (the incoming documentation PR will reflect that obviously)
- Add missing WebSocket constructor unit tests
- The `WebSocketClient` global is now an instance property, since it was overwritten each time a WebSocket class was instantiated anyway
=> [WebSocket] allow passing HTTP headers to the constructor

package-lock.json, package.json, src/Kuzzle.js, src/controllers/auth.js, src/controllers/base.js, src/controllers/bulk.js, src/controllers/collection.js, src/controllers/document.js, src/controllers/index.js, src/controllers/memoryStorage.js, src/controllers/realtime/index.js, src/controllers/searchResult/base.js, src/controllers/searchResult/profile.js, src/controllers/searchResult/role.js, src/controllers/searchResult/user.js, src/controllers/security/index.js, src/controllers/server.js, test/controllers/searchResult/document.test.js, test/controllers/searchResult/profile.test.js, test/controllers/searchResult/role.test.js, test/controllers/searchResult/specifications.test.js, test/controllers/searchResult/user.test.js, test/controllers/security.test.js, test/controllers/server.test.js, test/kuzzle/useController.test.js
- [ [#384](https://github.com/kuzzleio/sdk-javascript/pull/384) ] [fix] search API: "sort" and "search_after" must be in the requests body   ([scottinet](https://github.com/scottinet))
- [ [#388](https://github.com/kuzzleio/sdk-javascript/pull/388) ] Use BaseController class for controllers   ([Aschen](https://github.com/Aschen))
- [ [#385](https://github.com/kuzzleio/sdk-javascript/pull/385) ] Add Realtime.createRestrictedUser method   ([Aschen](https://github.com/Aschen))
- [ [#387](https://github.com/kuzzleio/sdk-javascript/pull/387) ] SearchResult.next returns a new instance   ([Aschen](https://github.com/Aschen))
---
=> Release 6.1.1

src/controllers/bulk.js, test/controllers/bulk.test.js
Fix bulk import erroneous return.
The document say that the methods returns `errors` and `items`: https://docs.kuzzle.io/sdk-reference/js/6/bulk/import/
=> Fix bulk return

.travis.yml
=> [CI] Fix documentation deployment conditions

.travis.yml
=> Reactivate documentation deployment

package-lock.json, package.json, src/protocols/websocket.js, test/protocol/websocket.test.js
- [ [#462](https://github.com/kuzzleio/sdk-javascript/pull/462) ] Fix erroneous error message on browser ws error   ([scottinet](https://github.com/scottinet))
---
=> Release 6.2.7

.travis.yml
Updates Travis condition to handle stable branches NPM.js deployments
=> Handle deployments on stable branches

package-lock.json, package.json, src/Kuzzle.js
- [ [#471](https://github.com/kuzzleio/sdk-javascript/pull/471) ] Fix option refresh in queries   ([Yoann-Abbes](https://github.com/Yoann-Abbes))
---
=> Release 6.2.8

.travis.yml, doc/7/controllers/security/create-or-replace-role/index.md, doc/7/controllers/security/create-role/index.md, doc/7/controllers/security/update-role/index.md, src/controllers/security/index.js, test/controllers/security.test.js
This PR adds a new `force` option to routes who write a role.
It permits not to throw in case you want to set rights about a plugin which is not available yet, or controllers/action that are not described yet in the plugin.
:warning:  This PR goes along with https://github.com/kuzzleio/kuzzle/pull/1535/
As you can see, this option is only effective if it concerns plugin rights. 
:warning: 
:warning: you should test it with Kuzzle instantiated on this branch https://github.com/kuzzleio/kuzzle/pull/1535/ :warning:
- Try creating this role
```
const body = { 
controller: {
unavailable_plugin/test: {
actions: {
create: true,
update: true
}
}
}
}
this.sdk.security.createRole('newRole', body) will throw.
this.sdk.security.createRole('newRole', body, {force: true}) will work
```
- Step 1 :
- …
=> Add a "force" option to create/update role

doc/7/controllers/collection/create/index.md
Fix ES website deadlink for v7
=> Fix ES website deadlink for v7

doc/6/controllers/collection/create/index.md
Fix ES website deadlink for v6.
=> Fix ES website deadlink for v6

doc/5/core-classes/collection-mapping/constructor/index.md, doc/5/core-classes/collection/create/index.md
Fix ES website deadlink for v5
=> Fix ES website deadlink for v5

index.js, src/controllers/document.js, src/controllers/searchResult/index.js
=> Allow better extensibility

doc/7/getting-started/react-native/index.md
Correctly adds empty lines between each snippet and the actual file content.
Fixes kuzzleio/documentation#454
_(Given that this Hotfix is to be merged into master, don't forget to also update 7-dev)_
=> Fix snippets on react native article

index.ts
Export types, classes and interfaces declared in `interfaces.ts`
=> Export interfaces

doc/7/controllers/document/m-get/index.md
This PR fixes a typo in the controller Document, mGet method documentation.
=> Fix typo mget doc

doc/7/controllers/auth/create-api-key/index.md, doc/7/controllers/auth/create-api-key/snippets/create-api-key.test.yml, doc/7/controllers/auth/delete-api-key/index.md, doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.test.yml, doc/7/controllers/auth/search-api-keys/index.md, doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-es.test.yml, doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-koncorde.test.yml, src/controllers/Auth.ts
Fix typo documentation
- Step 1 :
- Step 2 :
- Step 3 :  
...
=> Fix typo documentation

doc/7/controllers/auth/check-rights/index.md, doc/7/controllers/auth/check-rights/snippets/check-rights.js, doc/7/controllers/auth/check-rights/snippets/check-rights.test.yml, doc/7/controllers/document/upsert/index.md, doc/7/controllers/document/upsert/snippets/upsert.js, doc/7/controllers/document/upsert/snippets/upsert.test.yml, doc/7/controllers/security/check-rights/index.md, doc/7/controllers/security/check-rights/snippets/check-rights.js, doc/7/controllers/security/check-rights/snippets/check-rights.test.yml, package-lock.json, package.json, src/Kuzzle.ts, src/controllers/Auth.ts, src/controllers/Document.ts, src/controllers/Security.js, src/protocols/abstract/Base.ts, src/types/Document.ts
- [ [#577](https://github.com/kuzzleio/sdk-javascript/pull/577) ] Add [auth|security]:checkRights   ([Yoann-Abbes](https://github.com/Yoann-Abbes))
- [ [#576](https://github.com/kuzzleio/sdk-javascript/pull/576) ] Add document:upsert   ([Yoann-Abbes](https://github.com/Yoann-Abbes))
---
=> Release 7.5.0

doc/7/core-classes/search-result/properties/index.md, package-lock.json, package.json, src/core/searchResult/Document.ts, src/core/searchResult/Profile.ts, src/core/searchResult/Role.ts, src/core/searchResult/SearchResultBase.ts, src/core/searchResult/Specifications.ts, src/core/searchResult/User.ts, test/controllers/collection.test.js, test/controllers/document.test.js, test/controllers/security.test.js, test/core/searchResult/document.test.js, test/core/searchResult/profile.test.js, test/core/searchResult/role.test.js, test/core/searchResult/specifications.test.js, test/core/searchResult/user.test.js, webpack.config.js
Add support for ES suggesters (`suggest` keyword) 
See also https://github.com/kuzzleio/kuzzle/pull/2019
- reduce the bundle size by ignoring node packages for the web build `230KB => 137KB` (fix https://github.com/kuzzleio/sdk-javascript/issues/616)
=> Add suggest to search result

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Updates our contributing templates and makes use of GitHub contact links.
=> Update our CONTRIBUTING templates

.github/actions/tests-ac/action.yml, .github/workflows/pull_request.workflow.yml, .github/workflows/push_dev.workflow.yml, .github/workflows/push_master.workflow.yml, package-lock.json, package.json, src/utils/Deprecation.ts
- Transform src/... into ../...
- Comment Admin Console Test (for further modification)
=> Fix non relative import

doc/7/getting-started/.react-native/package-lock.json, doc/7/getting-started/.react-native/package.json, doc/7/getting-started/.react/with-redux/package.json, doc/7/getting-started/.vuejs/package-lock.json, doc/7/getting-started/.vuejs/package.json, package-lock.json, package.json, src/Kuzzle.ts, src/controllers/Auth.ts, src/controllers/Realtime.ts, src/protocols/WebSocket.ts, src/protocols/abstract/Realtime.ts, test/kuzzle/authenticator.test.js, test/kuzzle/listenersManagement.test.js, test/protocol/WebSocket.test.js
- [ [#653](https://github.com/kuzzleio/sdk-javascript/pull/653) ] Reconnect with authenticator when receiving TokenExpired event   ([Aschen](https://github.com/Aschen) & [Shiranuit](https://github.com/Shiranuit))
- [ [#653](https://github.com/kuzzleio/sdk-javascript/pull/653) ] Fix SDK emitting reconnect event twice caused by closing Websocket ([Shiranuit](https://github.com/Shiranuit))
- [ [#653](https://github.com/kuzzleio/sdk-javascript/pull/653) ] Fix SDK emitting disconnect event at each reconnection attempt that failed ([Shiranuit](https://github.com/Shiranuit))
---
=> Release 7.7.3

doc/7/controllers/document/upsert/index.md, doc/7/protocols/http/constructor/index.md, doc/7/protocols/http/constructor/snippets/constructor.js, package-lock.json, package.json, src/controllers/Document.ts, src/protocols/Http.ts, test/controllers/document.test.js, test/protocol/Http.test.js
- [ [#660](https://github.com/kuzzleio/sdk-javascript/pull/660) ] Fix upsert options.default    ([Aschen](https://github.com/Aschen))
- [ [#661](https://github.com/kuzzleio/sdk-javascript/pull/661) ] Allows to define custom headers for HTTP protocol   ([Aschen](https://github.com/Aschen))
---
=> Release 7.7.5

.github/actions/tests-ac/action.yml, package-lock.json, package.json, src/core/Observer.ts
=> Release 7.8.1: Fix bad import

doc/7/controllers/document/search/index.md, doc/7/essentials/realtime-application/index.md
Improve documentation for the `next` method
=> Improve document search doc

src/Kuzzle.ts, src/controllers/Auth.ts
This PR adds a verification when using checkToken to verify that the informations about the token validity are not from the anonymous token.
=> Fix authenticator token verification

src/controllers/Auth.ts, src/controllers/Bulk.ts, src/controllers/Document.ts, src/controllers/Security.ts, src/core/batchWriter/BatchWriter.ts
Fix the `refresh` arg type to accept `"false"`
=> Fix refresh arg type

doc/7/controllers/index.md, doc/7/core-classes/base-controller/index.md, doc/7/core-classes/batch-controller/index.md, doc/7/core-classes/kuzzle-error/index.md, doc/7/core-classes/kuzzle-event-emitter/index.md, doc/7/core-classes/kuzzle-event-emitter/introduction/index.md, doc/7/core-classes/kuzzle/index.md, doc/7/core-classes/observer/index.md, doc/7/core-classes/profile/index.md, doc/7/core-classes/role/index.md, doc/7/core-classes/search-result/index.md, doc/7/core-classes/user/index.md, doc/7/essentials/events/index.md, doc/7/essentials/index.md, doc/7/getting-started/index.md, doc/7/protocols/http/index.md, doc/7/protocols/index.md, doc/7/protocols/websocket/index.md
Fix bad links in the documentation
=> Fix Bad links in the Kuzzle event documentation

package-lock.json, package.json, src/types/index.ts
Expose the `ResponsePayload` type
=> 7.10.2 - Expose ResponsePayload

package-lock.json, package.json, src/types/KDocument.ts
- [ [#726](https://github.com/kuzzleio/sdk-javascript/pull/726) ] Add index and collection fields to KHit   ([fmauNeko](https://github.com/fmauNeko))
---
=> Release 7.10.8

doc/7/controllers/document/delete-fields/snippets/deleteFields.test.yml, doc/7/controllers/document/exists/index.md, doc/7/controllers/document/exists/snippets/exists.js, doc/7/controllers/document/exists/snippets/exists.test.yml
* This PR adds the documentation that was missing from the exists method inside this sdk
=> chore(documentation): Add exists documentation

doc/7/getting-started/index.md, doc/7/getting-started/node-js/index.md, doc/7/getting-started/node-js/snippets/create.js, doc/7/getting-started/node-js/snippets/create.test.yml, doc/7/getting-started/node-js/snippets/init.js, doc/7/getting-started/node-js/snippets/init.test.yml, doc/7/getting-started/node-js/snippets/load-sdk.js, doc/7/getting-started/node-js/snippets/load-sdk.test.yml, doc/7/getting-started/node-js/snippets/prepare-db.js, doc/7/getting-started/node-js/snippets/prepare-db.test.yml, doc/7/getting-started/node-js/snippets/subscribe.js, doc/7/getting-started/node-js/snippets/subscribe.test.yml, doc/7/getting-started/raw-web/index.md, doc/7/getting-started/raw-web/snippets/create.html, doc/7/getting-started/raw-web/snippets/create.test.yml, doc/7/getting-started/raw-web/snippets/load-sdk.html, doc/7/getting-started/raw-web/snippets/load-sdk.test.yml, doc/7/getting-started/raw-web/snippets/prepare-db.html, doc/7/getting-started/raw-web/snippets/prepare-db.test.yml, doc/7/getting-started/raw-web/snippets/subscribe.html, doc/7/getting-started/raw-web/snippets/subscribe.test.yml, doc/7/getting-started/webpack/index.md, doc/7/getting-started/webpack/snippets.disabled/create.js, doc/7/getting-started/webpack/snippets.disabled/create.test.yml, doc/7/getting-started/webpack/snippets.disabled/init-kuzzle.js, doc/7/getting-started/webpack/snippets.disabled/init-kuzzle.test.yml, doc/7/getting-started/webpack/snippets.disabled/subscribe.js, doc/7/getting-started/webpack/snippets.disabled/subscribe.test.yml
=> docs(getting-started): add some getting started

doc/7/getting-started/index.md, doc/7/getting-started/node-js/index.md, doc/7/getting-started/node-js/snippets/create.js, doc/7/getting-started/node-js/snippets/create.test.yml, doc/7/getting-started/node-js/snippets/init.js, doc/7/getting-started/node-js/snippets/init.test.yml, doc/7/getting-started/node-js/snippets/load-sdk.js, doc/7/getting-started/node-js/snippets/load-sdk.test.yml, doc/7/getting-started/node-js/snippets/prepare-db.js, doc/7/getting-started/node-js/snippets/prepare-db.test.yml, doc/7/getting-started/node-js/snippets/subscribe.js, doc/7/getting-started/node-js/snippets/subscribe.test.yml, doc/7/getting-started/raw-web/index.md, doc/7/getting-started/raw-web/snippets/create.html, doc/7/getting-started/raw-web/snippets/create.test.yml, doc/7/getting-started/raw-web/snippets/load-sdk.html, doc/7/getting-started/raw-web/snippets/load-sdk.test.yml, doc/7/getting-started/raw-web/snippets/prepare-db.html, doc/7/getting-started/raw-web/snippets/prepare-db.test.yml, doc/7/getting-started/raw-web/snippets/subscribe.html, doc/7/getting-started/raw-web/snippets/subscribe.test.yml, doc/7/getting-started/webpack/index.md, doc/7/getting-started/webpack/snippets.disabled/create.js, doc/7/getting-started/webpack/snippets.disabled/create.test.yml, doc/7/getting-started/webpack/snippets.disabled/init-kuzzle.js, doc/7/getting-started/webpack/snippets.disabled/init-kuzzle.test.yml, doc/7/getting-started/webpack/snippets.disabled/subscribe.js, doc/7/getting-started/webpack/snippets.disabled/subscribe.test.yml, src/controllers/Document.ts
=> Add getting started

package-lock.json, package.json
This PR fixes a vulnerability of ws, affected by a DoS when handling a request with many HTTP headers.
Linked to [KZLPRD-624](https://kuzzle.atlassian.net/browse/KZLPRD-624).
[KZLPRD-624]: https://kuzzle.atlassian.net/browse/KZLPRD-624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ws vulnerability

src/controllers/Security.ts
Only add default to checkRights options
=> fix: add default options to security:checkRights
