kuzzleio/sdk-javascript

- src/kuzzle.js
Fixes #8.
Forces Kuzzle constructor to return a valid Kuzzle instance if not called using the new keyword.
> issue #8 - Kuzzle constructor called without new keyword

- package.json
- src/kuzzle.js
- test/kuzzle/constructor.test.js
Bugfixes: 
* listeners added on the global event handlers weren't called correctly
* state management made resubscription go in pending state forever when recovering from a connection loss
> a few bugfixes

- src/kuzzle.js
- test/kuzzle/methods.test.js
The `Kuzzle.checkToken` method should not take options, and it should always be non-queuable.
Moreover, instead of returning the raw API response, it now returns only the informations concerning the token check.
The SDK documentation will be updated accordingly.
> checkToken does not take options

- src/kuzzleDataCollection.js
- test/kuzzleDataCollection/constructor.test.js
- test/kuzzleDataCollection/methods.test.js
Following migration to ES 2.x, remove the call to the deleteCollection.
>  #kuz-465 remove deleteCollection

- src/kuzzle.js
- test/kuzzle/methods.test.js
Inverted the `index` and `collection` arguments of the `Kuzzle.dataCollectionFactory` method, to make the optional argument appear after the required one.
> fixes issue #81

- package.json
- src/kuzzle.js
- test/kuzzle/constructor.test.js
- test/kuzzle/methods.test.js
Instead of being read-only, the `host`, `ioPort` and `wsPort` attributes from the `Kuzzle` object should be writable to allow changing them between connections.
And when invoking `Kuzzle.connect`, if a network connection has previously been established, then `Kuzzle.disconnect` is called beforehand.
> [MASTER] KUZ-683 allow changing host

- package.json
- src/kuzzle.js
- test/kuzzle/constructor.test.js
- test/kuzzle/methods.test.js
Instead of being read-only, the `host`, `ioPort` and `wsPort` attributes from the `Kuzzle` object should be writable to allow changing them between connections.
And when invoking `Kuzzle.connect`, if a network connection has previously been established, then `Kuzzle.disconnect` is called beforehand.
> [DEVELOP] KUZ-683 allow changing host

- src/kuzzleSubscribeResult.js
- test/kuzzleSubscribeResult/kuzzleSubscribeResult.test.js
This PR ensures the subscription callbacks are correctly called in the unlikely event of invoking the `onDone` method _after_ Kuzzle responds.
For instance, if one stores the `KuzzleDataCollection.subscribe` or the `KuzzleDocument.subscribe` result, and then invokes its `onDone` method a few milliseconds after that.
> make subscribe.onDone foolproof

- src/Kuzzle.js
- test/kuzzle/query.test.js
Fix #168 
Instead of silently discarding requests during offline mode with no queue option activated, it now explicitly rejects them, allowing clients to catch the error and act accordingly.
Other bugfix: it was also silently discarding requests during offline mode, if queue option is false but the request itself was passed with the `queuable` option set to true
> fix #168 - now rejects requests when no other option is possible

- package.json
- src/SearchResult.js
When from was equal to 0, the property was not removed properly.
> Fix the next method in searchResult

- package.json
- src/Room.js
- test/Room/methods.test.js
Fix #178 
Notification object for `realtime/publish` action now contains a `document` attribute, containing a `Document`object with the content of the published message.
> Fix 178 realtime notification

- README.md
- src/Kuzzle.js
- src/networkWrapper/index.js
- test/kuzzle/constructor.test.js
Following https://github.com/kuzzleio/kuzzle-proxy/pull/48
Now, Kuzzle will listen to the same port for both protocols.
This fixes the default config as well as the documentation.
TODO after merging this PR: "un-wip" the related PR on Backoffice: https://github.com/kuzzleio/kuzzle-backoffice/pull/213 (+ update the sdk version dependency into it)
> use 7512 port by default for both websocket and socketio

- package.json
- src/Kuzzle.js
- test/kuzzle/constructor.test.js
In some circumstances, we may want to use the same kuzzle object and change its options, for instance to switch to another environment.
This PR allows to update any possible option given to Kuzzle constructor.
Notably, this allows to switch the connection mode back from or to ssl on the current kuzzle instance, without having to create a new object.
kuzzleio/kuzzle-backoffice#154
* #188
* https://github.com/kuzzleio/documentation/pull/113
> Make all Kuzzle constructor options writable

- src/Kuzzle.js
- test/kuzzle/constructor.test.js
In some circumstances, we may want to use the same kuzzle object and change its options, for instance to switch to another environment.
This PR allows to update any possible option given to Kuzzle constructor.
Notably, this allows to switch the connection mode back from or to ssl on the current kuzzle instance, without having to create a new object.
https://github.com/kuzzleio/kuzzle-backoffice/issues/154
https://github.com/kuzzleio/documentation/pull/113
> Make all options given to kuzzle constructor writable

- README.md
- package.json
- src/Collection.js
- test/Collection/methods.test.js
Following https://github.com/kuzzleio/kuzzle/pull/709, the `scroll` option is now optional (!)
Also fix the way the query is built to make it consistent with the way `kuzzle.query` is meant to be used.
> [HOTFIX] Collection.scroll: the scroll parameter is now optional

- src/MemoryStorage.js
- test/MemoryStorage/constructor.test.js
- test/MemoryStorage/methods.test.js
- test/kuzzle/constructor.test.js
Make the `MemoryStorage` object on par with the newly refactored corresponding controller.
> Standardize memory storage object

- src/MemoryStorage.js
- test/MemoryStorage/methods.test.js
- test/kuzzle/constructor.test.js
The `ms.zscore()` method should return a floating point number, but redis sends a string response, so we need to interpret the result to return the right result type.
> Fix ms.zscore return value type

- src/MemoryStorage.js
- test/MemoryStorage/methods.test.js
(this PR should not appear in the changelog: it affects only the changes on the MemoryStorage controller in the `4.x` SDK version)
The `hgetall` result was interpreted as an array of, alternatively, key and its associated value, and a mapper function was plugged into this method to ensure a proper JSON object was returned to the client.
But the result of this redis call is already a POJO, so the mapping is unnecessary and causes a SDK crash.
> Fix ms.hgetall return value interpretation

- src/Collection.js
- test/Collection/methods.test.js
Add support for the new `retryOnConflict` option on the `collection.updateDocument` route
https://github.com/kuzzleio/kuzzle/issues/730
> Add support for the new retryOnConflict option

- src/Collection.js
- src/Document.js
- src/Kuzzle.js
- src/Room.js
- test/Room/constructor.test.js
- test/kuzzle/constructor.test.js
- test/kuzzle/methods.test.js
- test/kuzzle/query.test.js
:warning: Must be merged:
* https://github.com/kuzzleio/kuzzle-common-objects/pull/26
> Rename metadata into volatile

- src/security/Security.js
- test/security/kuzzleSecurity/userMethods.test.js
Linked to https://github.com/kuzzleio/kuzzle-sdk/issues/21
> Adds a new replaceUser method to Security

- src/Kuzzle.js
- src/Room.js
- src/eventEmitter/index.js
- src/networkWrapper/wrappers/websocket.js
- test/Room/methods.test.js
- test/kuzzle/constructor.test.js
- test/kuzzle/emitEvent.test.js
- test/kuzzle/listenersManagement.test.js
- test/network/websocket.test.js
main `Kuzzle` SDK prototype and websocket wrapper implementation both used their own event listeners.
Now, both Kuzzle and websocket wrapper inherits from Node build-in `EventEmitter` class (https://nodejs.org/api/events.html), with a polyfilled implementation for browser.
method `addListener` no longer returns an ID, to be compliant with NodeJS implementation ( https://nodejs.org/api/events.html#events_emitter_on_eventname_listener )
It now returns the Emitter object itself, so that it can be chained.
For each event, the listener callback function is used as the key in listeners list
https://github.com/kuzzleio/documentation/pull/172
>  Harmonize event emitters implementation

- src/Kuzzle.js
- test/kuzzle/methods.test.js
fix https://github.com/kuzzleio/kuzzle-sdk/issues/28
>  createIndex should only return response.result

- src/Kuzzle.js
- src/security/Security.js
- test/kuzzle/methods.test.js
- test/security/kuzzleSecurity/credentialsMethods.test.js
Creation of new actions in auth controller:
Creation of new actions in security controller:
> Added all new credential related routes

- src/Kuzzle.js
- test/kuzzle/login.test.js
:warning: This PR depends on kuzzleio/kuzzle#840
Reshapes the login call according to the PR kuzzleio/kuzzle#840
* The SDK now throws if no strategy is specified in the `login` call.
> Login reshape

- src/networkWrapper/wrappers/websocket.js
The `networkError` event has an inconsistent payload: the main `Kuzzle` object may trigger it with an `Error` object (if unable to establish a connection), but the `websocket` wrapper triggers it with a `string` message if the socket gets unexpectedly closed.
> networkError payload should be an Error object

- README.md
- package.json
- src/security/User.js
- test/security/kuzzleUser/methods.test.js
* `User.getProfiles` is renamed to `User.getProfileIds`
* `User.getProfileIds` now returns an empty array instead of `undefined` if no profile is attached to the user object
* add a new `User.getProfiles` method fetching profiles from Kuzzle API and returning an array of `Profile` objects
Update README file
https://github.com/kuzzleio/kuzzle-sdk/issues/33
> Rename getProfiles to getProfileIds and add a proper getProfiles method

- src/Collection.js
- test/Collection/constructor.test.js
- test/Collection/methods.test.js
- Document;m* methods support (related to https://github.com/kuzzleio/kuzzle/pull/616)
- Corresponding unit tests
> Add support for Document:m* methods

- package.json
- src/MemoryStorage.js
- test/MemoryStorage/methods.test.js
Following the work done in https://github.com/kuzzleio/documentation/pull/281, the returned values of `MemoryStorage.*scan` methods has been changed.
This PR updates the SDK to make it match the new return value format for these methods.
**Note:** this will trigger a patch version update on this SDK (5.0.2), as the published 5.x version is not usable until Kuzzle RC10 is out
> Update MemoryStorage.*scan return value format

- src/security/Security.js
- test/security/kuzzleSecurity/profilesMethods.test.js
Following https://github.com/kuzzleio/sdk-android/pull/133#pullrequestreview-42261560, the `Security.createProfile` and `Security.updateProfile` methods now take a `policies` argument, which is an array of policies to apply to the corresponding profile, instead of a `content` argument, an object containing a `policies` key containing the list of policies to apply.
> Fix createProfile and updateProfile method signatures

- src/Kuzzle.js
- src/Room.js
- test/Room/methods.test.js
- test/kuzzle/connect.test.js
- test/kuzzle/listenersManagement.test.js
- test/kuzzle/query.test.js
Following https://github.com/kuzzleio/kuzzle/pull/882, the SDK JS gets an update to make it able to handle the new notifications format.
Also, the `jwtTokenExpired` event has been renamed `tokenExpired`.
> Update to new notifications format

- package-lock.json
- package.json
- src/Collection.js
- src/Kuzzle.js
- src/MemoryStorage.js
- src/Room.js
- src/security/Security.js
- test/Collection/constructor.test.js
- test/Collection/methods.test.js
- test/Room/methods.test.js
- test/kuzzle/connect.test.js
- test/kuzzle/constructor.test.js
- test/kuzzle/listenersManagement.test.js
- test/kuzzle/login.test.js
- test/kuzzle/methods.test.js
- test/kuzzle/query.test.js
| Kuzzle | Proxy |
|--------|-------|
| 1.0.0 | 1.0.0 |
- [ [#234](https://github.com/kuzzleio/sdk-javascript/pull/234) ] Update to new notifications format & event rename ([scottinet](https://github.com/scottinet))
- [ [#230](https://github.com/kuzzleio/sdk-javascript/pull/230) ] Fix createProfile and updateProfile method signatures ([scottinet](https://github.com/scottinet))
- [ [#228](https://github.com/kuzzleio/sdk-javascript/pull/228) ] Remove fetchAllDocuments method ([benoitvidis](https://github.com/benoitvidis))
- [ [#227](https://github.com/kuzzleio/sdk-javascript/pull/227) ] Update MemoryStorage.*scan return value format ([scottinet](https://github.com/scottinet))
- [ [#225](https://github.com/kuzzleio/sdk-javascript/pull/225) ] Rename getProfiles to getProfileIds and add a …
> Release: 5.0.4

- src/Kuzzle.js
- test/kuzzle/query.test.js
- webpack.config.js
- Adds the current version of the SDK into volatile for every Kuzzle query.
- Modified webpack config to integrate the version at build time.
> Add SDK version into volatile

- src/Collection.js
- src/Kuzzle.js
- src/security/Profile.js
- src/security/Role.js
- src/security/Security.js
- src/security/SecurityDocument.js
- src/security/User.js
- test/security/kuzzleProfile/methods.test.js
- test/security/kuzzleRole/methods.test.js
- test/security/kuzzleUser/methods.test.js
- Meta in Security documents (User, Profile, Role)
**Should only be merged after Kuzzle side PR**
https://github.com/kuzzleio/kuzzle/pull/897
> Add meta to Security documents (User, Profile, Role)

- README.md
- src/Collection.js
- src/SearchResult.js
- test/SearchResult/methods.test.js
- Way to use ES's search_after if conditions are met when calling SearchResult:fetchNext (better than using scrolls, bypasses the default search limit count)
https://github.com/kuzzleio/kuzzle/issues/856
- Updates README.md (typos / various)
> Allow paginated search using ES's search_after in SearchResult:fetchNext

- src/Kuzzle.js
- test/kuzzle/login.test.js
fix https://github.com/kuzzleio/kuzzle-sdk/issues/39
> Login: move "expiresIn" option from request.body to request root attribute

- src/Kuzzle.js
- src/Room.js
replace deprecated syntax:
```javascript
var
uuid = require('uuid'),
generatedUuid = uuid.v4();
```
by new one:
```javascript
var
uuidv4 = require('uuid/v4'),
generatedUuid = uuidv4();
```
(see https://www.npmjs.com/package/uuid#deprecated--browser-ready-api)
> Fix uuid API

- src/Room.js
- test/Room/methods.test.js
Fixes in the way the JS SDK handles the User Notification response.
See changes in the documentation PR: https://github.com/kuzzleio/documentation/pull/330
> Fixed User Notification response format

- src/Kuzzle.js
- test/kuzzle/query.test.js
While invoking `kuzzle.disconnect()` correctly closes the network connection and prepare Kuzzle so that nothing stay on the event loop, the clean history timer still runs indefinitely.
This means that, without using `process.exit`, it is impossible to make a program stop when a Kuzzle instance is created.
This PR adds a property keeping track of the history timer, and makes the disconnect method remove the timer, leaving nothing on the event loop after been called
> Remove cleanHistory from event loop upon disconnection

- index.js
- webpack.config.js
By injecting a `BUILT` constant via Webpack, and by checking the `window` global, we are able to detect if the user is using the Nodejs version in the browser.
> Throw when using Nodejs version in browser

- src/MemoryStorage.js
- test/MemoryStorage/methods.test.js
* MS functions returning either `0` or `1` are now resolving to a boolean value instead of an integer
* MS functions returning `"OK"` now resolves to a `function (err, undefined)` callback (or an empty thenable when promisified)
> Harmonize values returned by memory storage functions

- LICENSE.md
- src/Collection.js
- src/CollectionMapping.js
- src/Document.js
- src/Kuzzle.js
- src/MemoryStorage.js
- src/Room.js
- src/networkWrapper/protocols/abstract/realtime.js
- test/Collection/constructor.test.js
- test/CollectionMapping/constructor.test.js
- test/CollectionMapping/methods.test.js
- test/Document/constructor.test.js
- test/Document/methods.test.js
- test/MemoryStorage/constructor.test.js
- test/Room/constructor.test.js
- test/Room/methods.test.js
- test/kuzzle/constructor.test.js
- test/kuzzle/methods.test.js
- test/kuzzle/query.test.js
- test/kuzzle/subscribe.test.js
- test/mocks/collection.mock.js
- test/mocks/kuzzle.mock.js
- test/network/socketio.test.js
- test/network/websocket.test.js
- expose the missing object properties expected by the current SDK specifications, with the right read/write attributes
- kuzzle object:
- autoQueue (writable)
- autoReconnect (changed to read-only)
- autoReplay (writable)
- host (read-only)
- offlineQueue (changed to read-only)
- offlineQueueLoader (writable)
- port (read-only)
- queueFilter (writable)
- queueMaxSize (writable)
- queueTTL (writable)
- replayInterval (writable)
- reconnectionDelay (changed to read-only)
- sslConnection (read-only)
- `Room` object: 
- `roomId` is now a read-only property, and is not used as an internal flag to check if a subscription is active. Instead, a new private `active` boolean property has been added for that purpose
- `scope`, `state` and `users` are now enumerable
- `autoResubscribe` is now …
> Fix exposed object properties

- src/Kuzzle.js
- test/kuzzle/methods.test.js
As [getStats](http://docs.kuzzle.io/api-documentation/controller-server/get-stats/) API method accept both a `startTime` and a `stopTime` arguments, we should also accept a `stopTime` parameter in the SDK
Fix https://github.com/kuzzleio/kuzzle-sdk/issues/63
> add `stopTime` as optional argument for `getStatistics()`

- src/Kuzzle.js
- src/networkWrapper/protocols/abstract/realtime.js
- test/SearchResult/methods.test.js
- test/kuzzle/query.test.js
- test/network/query.test.js
V6.x version of https://github.com/kuzzleio/sdk-javascript/pull/268
> V6: Option "subscribeToSelf" using volatile data

- package-lock.json
- package.json
Update `ws` version from `3.0.0` to `3.3.1` due to security reason (DOS) : https://nodesecurity.io/advisories/550
> [Hotfix] Security update ws to 3.3.1

- index.js
- src/Kuzzle.js
- src/networkWrapper/index.js
- src/networkWrapper/protocols/abstract/common.js
- src/networkWrapper/protocols/abstract/realtime.js
- src/networkWrapper/protocols/http.js
- src/networkWrapper/protocols/socketio.js
- src/networkWrapper/protocols/websocket.js
- test/kuzzle/connect.test.js
- test/kuzzle/constructor.test.js
- test/kuzzle/getters.test.js
- test/kuzzle/listenersManagement.test.js
- test/kuzzle/network.test.js
- test/kuzzle/query.test.js
- test/kuzzle/setters.test.js
- test/mocks/networkWrapper.mock.js
- test/network/http.test.js
- test/network/networkWrapper.test.js
- test/network/offlineQueue.test.js
- test/network/socketio.test.js
- test/network/websocket.test.js
See [KZL-175](https://jira.kaliop.net/browse/KZL-175)
Change the signature of SDK constructor to match actual signature in Go SDK and enable developers to instantiate the SDK with their custom network protocol:
```js
// Before: 
const kuzzle = new Kuzzle('hostname', {protocol: 'websocket'});
// Now - with embed protocol:
const kuzzle = new Kuzzle('websocket', {host: 'hostname'});
// Now - with custom protocol:
const protocol = new MyCustomProtocol();
const kuzzle = new Kuzzle(protocol, {});
```
Expose also `AbstractNetwork` and `KuzzleEventEmitter`:
Thus, custom protocol can easily inherits from `AbstractNetwork` and only implements `connect` and `send` methods:
```js
const
Kuzzle = require('kuzzle-sdk').Kuzzle,
KuzzleAbstractNetwork = require('kuzzle-sdk').KuzzleAbstractNetwork;
class …
```
> Allow passing a custom network object to Kuzzle SDK constructor

- package-lock.json
- package.json
- src/controllers/collection.js
- test/controllers/collection.test.js
The API route `collection:create` can be used with a mapping since Kuzzle 1.3.0, allowing the creation of a collection directly with a mapping specified: https://docs.kuzzle.io/api-documentation/controller-collection/create
This feature is missing from SDKs, and this PR fixes that for the version 6 of this SDK
* Dependencies update
* This package's version number in `package.json` and `package-lock.jon` files has been changed to `6.0.0` (prev. value: `5.0.11`)
> [6.x] collection.create can be used with a mapping

- src/Kuzzle.js
- src/controllers/auth.js
- src/controllers/bulk.js
- src/controllers/collection.js
- src/controllers/document.js
- src/controllers/index.js
- src/controllers/memoryStorage.js
- src/controllers/realtime/index.js
- src/controllers/realtime/room.js
- src/controllers/searchResult/base.js
- src/controllers/security/index.js
- src/controllers/server.js
- test/controllers/auth.test.js
- test/controllers/bulk.test.js
- test/controllers/collection.test.js
- test/controllers/document.test.js
- test/controllers/index.test.js
- test/controllers/realtime.test.js
- test/controllers/realtime/room.test.js
- test/controllers/searchResult/document.test.js
- test/controllers/searchResult/profile.test.js
- test/controllers/searchResult/role.test.js
- test/controllers/searchResult/specifications.test.js
- test/controllers/searchResult/user.test.js
- test/controllers/security.test.js
- test/controllers/server.test.js
- test/kuzzle/query.test.js
Make kuzzle.query return value consistent with other sdks, and give access to the whole Kuzzle response.
Given we have following response from Kuzzle:
```json
{
"status": 200,
"error": null,
"result": {"foo": "bar"},
"volatile": {"you": "'win"}
}
```
Before this PR: 
* `kuzzle.query` resolved only the result (`{foo: 'bar'}`)
* Some actions resolved directly the result from `Kuzzle.query`
example: `server.getAllStats` (https://github.com/kuzzleio/sdk-javascript/blob/6.x/src/controllers/server.js#L49 ):
```javascript
return this.kuzzle.query({
controller: 'server',
action: 'getAllStats'
}, options);
```
* Some other parsed the query result to resolve the pertinent value (exemlpe
example: `server.now` (https://github.com/kuzzleio/sdk-javascript/blob/6.x/src/controllers/server.js#L118): …
> Make kuzzle.query return the full response object from Kuzzle backend

- src/networkWrapper/protocols/http.js
- test/network/http.test.js
fix #292
inject `Content-length` header only in nodejs implemenation
(in browser mode, this header is automatically injected by the browser and should not be changed)
> [HTTP] Do not send unsafe headers in browser mode

- .travis.yml
- README.md
- deploy.sh
This PR update the README to briefly explain how to use the SDK V6 until the documentation is available.
- Step 1 : Read the readme, try the code example
- update deploy script (the one who build the `dist/`) to support the `6-beta` branch
- cosmetics on `.travis.yml`
> KZL 174 - Update README for SDK V6

- src/controllers/collection.js
- test/controllers/collection.test.js
This PR rename the method `deleteSpecification` of collection controller to `deleteSpecifications` to match the API (https://docs.kuzzle.io/api-documentation/controller-collection/delete-specifications)
> Rename deleteSpecification to deleteSpecifications

- src/Kuzzle.js
- src/networkWrapper/protocols/abstract/common.js
- src/networkWrapper/protocols/abstract/realtime.js
- src/networkWrapper/protocols/http.js
This PR removes some unused properties from the SDK
1. `Kuzzle.network.id` is never used. Further, being defined in the module scope, its value would have been the same between several Kuzzle isntances sharing the same require
2. The attempt to make the getters enumerable just don't work.
> remove unused properties

- src/Kuzzle.js
Fix a bug where the JWT would not be set if the controller would be `auth` and the action different from `checkToken`
> fix jwt in query

- package-lock.json
- package.json
- src/Kuzzle.js
- src/controllers/collection.js
- src/networkWrapper/protocols/abstract/common.js
- src/networkWrapper/protocols/abstract/realtime.js
- src/networkWrapper/protocols/http.js
- test/controllers/collection.test.js
- [ [#315](https://github.com/kuzzleio/sdk-javascript/pull/315) ] Fix jwt in query   ([jenow](https://github.com/jenow))
- [ [#312](https://github.com/kuzzleio/sdk-javascript/pull/312) ] Rename deleteSpecification to deleteSpecifications   ([Aschen](https://github.com/Aschen))
- [ [#313](https://github.com/kuzzleio/sdk-javascript/pull/313) ] Remove unused properties   ([benoitvidis](https://github.com/benoitvidis))
---
> Release 6.0.0-beta-2

- src/controllers/document.js
- test/controllers/document.test.js
This PR aligns the result of the  `document:delete` with the other sdks by returning the id of the deleted document.
> document:delete to return the id of the deleted document

- src/controllers/collection.js
- test/controllers/collection.test.js
Before the method `validateSpecifications` didn't take an index an a collection in parameters and could be used for any collection.  
This PR change the signature to match the rest of the collection controller. The method now take an index and a collection in addition to the specifications for this collection.
I also modify the `updateSpecifications` method. The method was taking an index and collection in parameter but it didn't scope the specifications to the collection. 
Related PR: https://github.com/kuzzleio/sdk-javascript/pull/318, https://github.com/kuzzleio/sdk-go/pull/211, https://github.com/kuzzleio/sdk-c/pull/13, https://github.com/kuzzleio/sdk-cpp/pull/11, https://github.com/kuzzleio/sdk-java/pull/13, https://github.com/kuzzleio/documentation-V2/pull/51
- Step 1 : Create …
> KZL-547 - Update validateSpecifications signature to take index and collection

- src/controllers/index.js
- test/controllers/index.test.js
This PR fix the return value for index#list and index#mDelete.  
They now returns array of strings instead of an object containing only one property.
- Step 1 : Create some indexes `for i in {1..10}; do; curl -H "Content-Type: application/json" -X POST "http://localhost:7512/test$i/_create" &; sleep 0.05; done`
- Step 2 : List them `await kuzzle.index.list() ` and check return value
- Step 3 : Delete them `await kuzzle.index.mDelete(['test1', 'test2']) and check return value
> Fix return value for index#list and index#mDelete

- src/controllers/document.js
- test/controllers/document.test.js
This PR fixes the output format  of the `document.deleteByQuery` to return an array of delete ids instead of the api result object.
Related: https://github.com/kuzzleio/documentation/pull/540
> deleteByQuery - return value

- package-lock.json
- src/controllers/searchResult/base.js
- src/controllers/searchResult/document.js
- src/controllers/searchResult/profile.js
- src/controllers/searchResult/role.js
- src/controllers/searchResult/specifications.js
- src/controllers/searchResult/user.js
- test/controllers/collection.test.js
- test/controllers/document.test.js
- test/controllers/searchResult/document.test.js
- test/controllers/searchResult/profile.test.js
- test/controllers/searchResult/role.test.js
- test/controllers/searchResult/specifications.test.js
- test/controllers/searchResult/user.test.js
- test/controllers/security.test.js
This PR slightly modifies the `SearchResult` objects by
- (cosmetic) making internal properties pseudo-private to get a more readable console.log
- add the aggregations support
> SearchResult - mark internal properties as pseudo-private + aggregation support

- src/networkWrapper/protocols/http.js
- test/network/http.test.js
This PR prevent to add `null` or `undefined` arguments to the query args in http protocol.
Fix #324 
Run this snippet at the root of `sdk-javascript` folder, the document id should not be the string `'null'`:
```javascript
const Kuzzle = require('./index').Kuzzle;
const kuzzle = new Kuzzle('http', { host: 'localhost', port: 7512 });
(async () => {
try {
await kuzzle.connect()
await kuzzle.index.create('index');
await kuzzle.collection.create('index', 'collection');
const doc = await kuzzle.document.create(
'index',
'collection',
null,
{ hello: 'world' },
{ refresh: 'wait_for' }
);
console.log(doc);
const document = await kuzzle.document.get('index', 'collection', doc._id);
console.log(document);
} catch (error) {
console.log(error);
}
})()
```
> Fix null id in arguments

- src/controllers/realtime/index.js
- test/controllers/realtime.test.js
The following methods are deprecated and will be removed in Kuzzle v2 so there is no need to keep them in the SDK : 
- `realtime:list`
- `realtime:validate`
> Remove realtime deprecated methods

- src/controllers/realtime/index.js
- test/controllers/realtime.test.js
This PR makes `realtime::subscribe` javascript API consistent with other langages.
Instead of resolving to the object `{ channel: 'foo', roomId: 'bar' }`, it resolves to 'bar'
You can now unsubscribe directly with the result of subscribe
> realtime: fix bug

- src/controllers/realtime/room.js
Fix exception when subscribed to a channel in which someone publish a message using REST API
See https://jira.kaliop.net/browse/KZL-791
Use the following client :+1: 
``` JS
const Kuzzle  = require('kuzzle-sdk').Kuzzle;
const kuzzle = new Kuzzle('websocket', {host: 'localhost'});
async function run() {
const roomID = await kuzzle.realtime.subscribe('obix', 'firmwares', {}, (r) => {
console.log(r);
})
await kuzzle.realtime.publish('obix', 'firmware', {msg: 'hello world'})
}
run()
```
Use rest API to publish a message:
``` HTTP
POST http://localhost:7512/obix/firmwares/_publish HTTP/1.1
Content-Type: application/json
{
"msg" : "Heelo REST API"
}
```
=> No more exception
> Kzl 791 fix exception when publish msg with rest api

- src/controllers/auth.js
- src/controllers/index.js
- test/controllers/auth.test.js
- test/controllers/index.test.js
Simplify returned values for the following methods:
- `index:delete`
- `index:setAutoRefresh`
- `index:refreshInternal`
- `index:refresh`
- `auth:deleteMyCredentials`
> Change incoherent method returns

- package-lock.json
- src/controllers/searchResult/base.js
- test/controllers/searchResult/document.test.js
- test/controllers/searchResult/profile.test.js
- test/controllers/searchResult/specifications.test.js
- test/controllers/searchResult/user.test.js
**:warning: depends on https://github.com/kuzzleio/sdk-javascript/pull/327**
Elasticsearch scroll method does not accept any other parameter than the scrollId. This PR only sends the proper parameters to the method.
> SearchResult - fix scroll next policy

- src/controllers/auth.js
- src/controllers/bulk.js
- src/controllers/collection.js
- test/controllers/auth.test.js
- test/controllers/bulk.test.js
- test/controllers/collection.test.js
When harmonizing the documentation for the SDJ JS 6, I noticed a few things that deserve to be corrected
- The method `auth:updateSelf` was returning a promise that resolve to a JSON object.  
:arrow_right:  Change the value resolved by the promise to a `User` object, like the `getCurrentUser` method
- The method `collection:updateSpecification` return an object containing the index and the collection where the specifications were updated. 
:arrow_right: Return only the updated specifications
- Step 1 : Run tests
> Harmonize SDK

- package-lock.json
- src/controllers/memoryStorage.js
- test/controllers/memoryStorage.test.js
The memory storage `sort` method is configured as a getter, meaning that its options are put at the root level of the sent json query. 
But, as stated by the [API documentation](https://docs-v2.kuzzle.io/api/1/controller-memory-storage/sort/), these options are expected in the "body" part of the request (because of the "store" option).
So, in its current state, options set for this command using the SDK are ignored by Kuzzle. 
This PR puts the options at their expected location, making Kuzzle correctly process the sort command.
> 'ms:sort' needs its options in the request's body

- src/Kuzzle.js
- src/networkWrapper/protocols/abstract/common.js
- test/network/http.test.js
- test/network/networkWrapper.test.js
- test/network/socketio.test.js
- test/network/websocket.test.js
I noticed that, in the `volatile` object in sent queries, the `sdkInstanceId` property was undefined. This is due to the missing unique `id` in the network objects.
This PR adds back the missing id to the base network class, as well as the corresponding unit tests.
Modernize some lines of codes here and there in the modified unit test files.
> Fix undefined "volatile.sdkInstanceId" in sent queries

- src/protocols/abstract/realtime.js
- test/protocol/websocket.test.js
Fix #343 unhandled rejection on connect retry.
- Step 1 : Run this snippet without Kuzzle running:
```js
const {
Kuzzle,
Websocket
} = require('./index');
const
websocketProtocol = new Websocket({ host: 'localhost', port: 7512 }),
kuzzle = new Kuzzle(websocketProtocol);
kuzzle.on('networkError', error => {
console.error(`Network Error: ${error.message}`);
});
(async () => {
try {
console.log(await kuzzle.server.now());
} catch (error) {
console.log(error);
} finally {
kuzzle.disconnect();
}
})()
```
> Fix 343 unhandled rejection on connect

- src/CollectionMapping.js
- test/CollectionMapping/methods.test.js
When calling getMapping on an aliased index, no result is returned.
This PR fixes this by assuming the returned index is the requested one (which is always the case).
> get mapping on aliased index

- README.md
- features/steps/document.js
- src/controllers/document.js
- test/controllers/document.test.js
Change parameters order for `collection:create` to put optional param in last position
- Step 1 :
- Step 2 :
- Step 3 :
> Put document:create optional args in last position

- README.md
- features/support/world.js
- index.js
- src/protocols/abstract/common.js
- src/protocols/abstract/realtime.js
- src/protocols/http.js
- src/protocols/index.js
- src/protocols/socketio.js
- src/protocols/websocket.js
- test/kuzzle/connect.test.js
- test/kuzzle/constructor.test.js
- test/kuzzle/getters.test.js
- test/kuzzle/protocol.test.js
- test/kuzzle/query.test.js
- test/kuzzle/queue.test.js
- test/kuzzle/setters.test.js
- test/mocks/protocol.mock.js
- test/protocol/http.test.js
- test/protocol/socketio.test.js
- test/protocol/websocket.test.js
The `host` param is now mandatory for protocols. The new constructor signature include mandatory `host` param and optional `options` param.
Documentation: https://github.com/kuzzleio/documentation-V2/pull/208
- Step 1 : Run tests
- Rename `Websocket` to `WebSocket`
- Update README: 
- link to doc v2
- fix examples
> Have host param mandatory for protocols

- package.json
Just add npm `prepublish` script to build dist before publish on npm to be able to use the sdk from a CDN (jsdelivr)
> [npm] Add prepulish script

- index.js
- src/Kuzzle.js
- src/controllers/base.js
- src/protocols/http.js
- test/kuzzle/useController.test.js
Adds a `useController` method to the Kuzzle object to use custom defined controllers.  
This allows to call plugin routes from the SDK without using the `query` method.
If I have a plugin with the following action: 
```
this.controllers = {
test: {
sayHello: 'sayHello'
}
};
this.routes = [
{ verb: 'get', url: '/test/sayHello', controller: 'test', action: 'sayHello' }
];
async sayHello (request) {
const message = request.input.args.message || request.input.body.message;
return message;
}
```
Then I can define the following custom controller and use it in the SDK:
```
class TestController extends BaseController {
constructor (accessor) {
super('ctoi-le-plugin/test', accessor);
}
sayHello (message, options) {
const request = {
action: 'sayHello',
body: {
message
}
};
return …
```
> Add method to use custom controllers in the SDK

- src/Kuzzle.js
Babel.js is not able to handle the async/await feature without a polyfill to be included along with the SDK on production.
Forcing the use of a polyfill is not a desired outcome for our SDK, so async/await is now a banned feature.
The "raw web" getting started tests are currently failing on the documentation because of this problem. Using this branch version solve the failing test.
> [es7] remove async/await

- src/controllers/realtime/index.js
- src/controllers/realtime/room.js
- test/controllers/realtime.test.js
- test/controllers/realtime/room.test.js
The Kuzzle event `tokenExpired` should be triggered in two cases:
* when a request response contains `tokenExpired` error
* whenever a `TokenExpired` realtime event is received
The current SDK version only handles the first case, which causes many problems for clients using realtime, such as:
* realtime callbacks are not cleared, meaning clients handling manually the event have more and more of the same callbacks registered (and invoked)
* the `tokenExpired` event is not triggered upon receiving a TokenExpired realtime notification
* the JWT is not cleared upon receiving a TokenExpired realtime notification
This PR adds a proper TokenExpired realtime notification handling, ensuring that all the above problems are solved.
> Properly handle tokenExpired events

- src/protocols/http.js
- src/protocols/routes.json
- test/protocol/http.test.js
Save Kuzzle API routes in a json file to permit the HTTP protocol to not have to performs request on Kuzzle to fetch all available `vanilla` routes.
Run Unit test and/or use HTTP protocol
> [KZL-996] Save Kuzzle API routes in a json file

- src/protocols/websocket.js
On a websocket connection error, the error thrown by the SDK has the following message: `[object Object]`
This is because on a connection error, `ws` sends a complex object, but our error handler processes it as if it's a string.
Run this snippet:
```js
const {Kuzzle, WebSocket} = require('kuzzle-sdk');
const
ws = new WebSocket('localhost'),
kuzzle = new Kuzzle(ws);
kuzzle.connect().catch(err => console.error(err));
kuzzle.disconnect();
```
Before this PR, this prints: 
```
Error: [object Object]
... stack trace ...
```
With this PR:
```
Error: WebSocket was closed before the connection was established
... stack trace ...
```
> WebSocket: fix error object on connection error

- src/KuzzleError.js
- src/protocols/abstract/common.js
- test/protocol/query.test.js
Adds a `KuzzleError` that extends `Error` class.  
The `KuzzleError` contains additional properties sent by Kuzzle: `status` and `stack`.
> KZL 1001 - Add KuzzleError

- package-lock.json
- src/KuzzleError.js
- test/protocol/query.test.js
This PR allows the sdk to get the additional `errors` and `count` properties when receiving a `PartialError` from Kuzzle.
> [bugfix] keep internal errors on PartialErrors

- features/steps/auth.js
- features/support/world.js
- package-lock.json
- package.json
- src/controllers/auth.js
- test/controllers/auth.test.js
:warning: depends on:
- https://github.com/kuzzleio/sdk-features/pull/4 : new test features
- https://github.com/kuzzleio/kuzzle/pull/1265 : actual `auth:refreshToken` API route
The CI will fail until the Kuzzle PR is merged.
Add support for the new `auth:refreshToken` API route.
* update the SDK features to the latest version and add support for the newest features added
> Add support for the new auth:refreshToken API route

- src/controllers/searchResult/base.js
- test/controllers/searchResult/document.test.js
- test/controllers/searchResult/profile.test.js
- test/controllers/searchResult/specifications.test.js
- test/controllers/searchResult/user.test.js
The `SearchResult` class sends a `search_after` request to Kuzzle upon calling its `next` method, if:
* no scroll_id is available
* a `size` option is provided
* the search query contains a `sort` modifier
The current implementation considers that `sort` must be at the root of the API request, while Kuzzle expects it inside the body part of it.
Same thing goes for the `search_after` argument, which must be put in the request body, not at root level.
> [fix] search API: "sort" and "search_after" must be in the requests body

- src/controllers/security/index.js
- test/controllers/security.test.js
Adds the method `realtime:createRestrictedUser`
- Step 1 : Run tests
> Add Realtime.createRestrictedUser method

- src/controllers/searchResult/base.js
- src/controllers/searchResult/profile.js
- src/controllers/searchResult/role.js
- src/controllers/searchResult/user.js
- test/controllers/searchResult/document.test.js
- test/controllers/searchResult/profile.test.js
- test/controllers/searchResult/role.test.js
- test/controllers/searchResult/specifications.test.js
- test/controllers/searchResult/user.test.js
Returns a new instance of `SearchResult` instead of mutating the existing object.
- Step 1 : Get a search result
- Step 2 : Use the `next` method to get the next search result
- Step 3 : The 2 objects are not the same
> SearchResult.next returns a new instance

- src/Kuzzle.js
- src/controllers/auth.js
- src/controllers/base.js
- src/controllers/bulk.js
- src/controllers/collection.js
- src/controllers/document.js
- src/controllers/index.js
- src/controllers/memoryStorage.js
- src/controllers/realtime/index.js
- src/controllers/security/index.js
- src/controllers/server.js
- test/controllers/server.test.js
- test/kuzzle/useController.test.js
*I'm not sure if this is a new feature or an enhancement* 
This PR intend to unify the way we add/use controllers with the SDK. In this way we can have the same API when using our core controllers (`document`, `collection`, etc.) and custom controllers made by users.  
All existing controllers are now inheriting from the `BaseController` class and they are added to the SDK with `Kuzzle.useController` instead of been manually instantiated.
Example of custom controller
```
class TaxiController extends BaseController {
constructor (kuzzle) {
super(kuzzle, 'my-plugin/taxi');
}
startDuty (driver) {
return this.query({ driver, action: 'startDuty' });
}
}
kuzzle.useController(TaxiController, 'taxi');
kuzzle.taxi.startDuty('Martin');
```
I know this look like a breaking change but since we never …
> Use BaseController class for controllers

- features/steps/collection.js
- src/Kuzzle.js
- src/protocols/abstract/common.js
- src/protocols/http.js
Add getter to know if the SDK is connected to a Kuzzle server or not.
This getter is just a wrapper around the `connected` getter of the underlying protocol.
`kuzzle.connected //=> true`
> Add isConnected

- src/controllers/document.js
- test/controllers/document.test.js
Explicitly declare default value for `from` and `size` in the request as specified in the documentation.  
We have to be explicit otherwise the `SearchResult` returned can not be used as usual with the `next()` method.
```
const result = await this.sdk.document.search(index, collection, { query: 'some query', sort: 'some sort'})
await result.next()
// Unable to retrieve next results from search: missing scrollId, from/sort, or from/size params\nThis is probably not a Kuzzle error, but a problem with a plugin implementation.
```
> Add default values for from/size to document:search

- src/controllers/searchResult/base.js
- test/controllers/searchResult/document.test.js
- test/controllers/searchResult/profile.test.js
- test/controllers/searchResult/specifications.test.js
- test/controllers/searchResult/user.test.js
According to ES documentation, `scroll` parameter should be sent again with `_search/scroll` api call, allowing us to choose smallest timeout for scroll to live on.
> Fix large document search using scroll

- src/proxify.js
Proxify  module use the object spread operator.  
Kuzzle use the Javascript SDK and we keep es5 compat so we have to keep the SDK Javascript es6compatible too.
> Fix incompatibility with ES6 Javascript

- src/controllers/security/index.js
- test/controllers/security.test.js
Make createUser id parametre optional as it is in the API.
```js
kuzzle.security.createUser(null, {
content: {
profileIds: ['default']
},
credentials: {
local: {
username: 'auto',
password: 'auto'
}
}
});
```
It should create a user with a generated id.
> Make createUser id parameter optional

- src/protocols/http.js
- test/protocol/http.test.js
When the `XmlHttpRequest` fail, the associated promise is never resolved nor rejected.  
It appear that the `XmlHttpRequest` fail in another thread so the `try ... catch` block fail to catch the associated error.  
This PR add a listener on `onreadystatechange` to reject the promise when the `XmlHttpRequest` is `done` and the status is `fail` .
Fix https://github.com/kuzzleio/sdk-javascript/issues/418
- Step 1 : Build the SDK `npm run build`
- Step 2 : Create the following webpage at the sdk repo root:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Kuzzle SDK Embedded</title>
<script type="text/javascript" src="dist/kuzzle.js"></script>
</head>
<body>
<button id="start" onclick="start()">Start</button>
<script type="text/javascript">
async function start() { …
```
> Fix http protocol unresolved promise on connection error

- doc/6/controllers/bulk/mWrite/index.md
- doc/6/controllers/bulk/mWrite/snippets/mWrite.js
- doc/6/controllers/bulk/mWrite/snippets/mWrite.test.yml
- doc/6/controllers/bulk/write/index.md
- doc/6/controllers/bulk/write/snippets/write.js
- doc/6/controllers/bulk/write/snippets/write.test.yml
- src/controllers/bulk.js
- test/controllers/bulk.test.js
Add `bulk:write` and `bulk:mWrite` support.  
I'm not sure if it's an enhancement or a new feature (it was a new feature in Kuzzle)
> Add bulk:write and bulk:mWrite

- src/core/Jwt.js
- test/core/Jwt.test.js
Since the SDK is available for Node.js and for browsers, the decoding of the JWT from base64 is done either with `Buffer.from(jwt, 'base64')` for Node.js or `atob(base64)` for browsers.  
The check to know the runtime was `if (Buffer)`, and since this class is undefined in the browsers, this line throw an exception who is catched by the `JSON.parse` `try...catch`.  
This PR fix the check to infer the runtime with `if (typeof Buffer !== 'undefined')` instead.
Fix #407 
- Step 1 : Create an this HTML file at the repository root and open it in your browser:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Kuzzle SDK Embedded</title>
<script type="text/javascript" src="dist/kuzzle.js"></script>
</head>
<body>
<button id="start" onclick="start()">Start</button>
<script …
```
> Fix bug when decoding JWT in browser

- doc/6/core-classes/kuzzle/disconnect/index.md
- src/protocols/abstract/common.js
- test/protocol/common.test.js
When a request is made to Kuzzle, we setup a once listener to handle the response. If a disconnection occur (manual with `disconnect()` or not), the listener are never freed.  
This PR save the pending requests in a `Map` and when a disconnection occur, a `discarded` event is triggered for each requests and then the map is cleared.
Fix #356 
- add .npmignore
> Prevent pending request leak when disconnect the SDK

- doc/6/essentials/events/index.md
- src/protocols/websocket.js
- test/protocol/websocket.test.js
Emit a `queryError` when receiving a response from a malformed request
Fix #357
> Emit queryError event on malformed request

- src/protocols/http.js
- test/protocol/http.test.js
HTTP querystrings do not define how boolean values should be encoded, how they are handled depend on the API parsing the querystring.
Kuzzle's convention is that, for booleans, option values are irrelevant. Instead, a boolean option is truthy if it' set in the querystring, and falsey otherwise.
So this: `url?foo=0` or `url?foo=false` makes Kuzzle interpret the `foo` option as a non-empty string, and thus as "true" when converted to a boolean.
This PR fixes how the SDK passes boolean options to the querystring, only setting one if it's truthy, and skipping it if it's not.
Use Kuzzle's CLI `createFirstAdmin` command: even if you tell it to not reset anonymous rights, it resets it because of that bug. If you apply these changes, the CLI acts as expected.
Add a missing unit test about how …
> Properly handle boolean flags in HTTP querystrings

- features/support/hooks.js
- package-lock.json
- package.json
- src/core/Jwt.js
- test/core/Jwt.test.js
React Native does not have the `Buffer` class or the `atob` function to decode base64 payload.  
This PR add a standalone base64 decoding function to ensure portability across platforms.
- Step 1 : Run unit tests
> Fix base64 decoding for the JWT in React Native

- doc/6/protocols/http/constructor/index.md
- doc/6/protocols/http/properties/index.md
- src/protocols/http.js
- test/protocol/http.test.js
Adds a connection timeout for http protocol
https://deploy-preview-439--doc-sdk-javascript.netlify.com/protocols/http/properties/
- Step 1 : instantiate the protocol with a timeout `new Http('localhost', { timeout: 1000 })`
- Step 2 :
- Step 3 :
> Add timeout support to Http protocol

- src/protocols/abstract/common.js
- test/protocol/common.test.js
The `kuzzle.connected` property which delegate to the protocol was testing a wrong `protocol.state` value (`'online'` instead of `'connected'`). 
6.x PR: https://github.com/kuzzleio/sdk-javascript/pull/452
> Fix connected property

- package-lock.json
- package.json
- src/protocols/abstract/common.js
- test/protocol/common.test.js
The `kuzzle.connected` property which delegate to the protocol was testing a wrong `protocol.state` value (`'online'` instead of `'connected'`). 
7.x PR: https://github.com/kuzzleio/sdk-javascript/pull/453
> Fix connected property value

- src/KuzzleError.js
- src/controllers/auth.js
- src/controllers/collection.js
- src/controllers/document.js
- src/controllers/index.js
- src/controllers/realtime/index.js
- src/controllers/security/index.js
- test/controllers/auth.test.js
- test/controllers/collection.test.js
- test/controllers/document.test.js
- test/controllers/index.test.js
- test/controllers/realtime.test.js
- test/controllers/security.test.js
`v6` version of #450 
Remove the local check of the arguments since now we have specifics errors code sent by Kuzzle.
- Add error codes `id` and `code` properties to `KuzzleError`
> Remove local checks for arguments 

- package-lock.json
- package.json
- src/protocols/abstract/realtime.js
- test/mocks/window.mock.js
- test/protocol/socketio.test.js
- test/protocol/websocket.test.js
If `autoReconnect` is true, the SDK tries to reconnect every `reconnectionDelay` milliseconds.
If executed within a browser, the SDK can know if the browser has access to some kind of network: if it's marked as "offline", then there is no point retrying to connect, and this might even be harmful in some situations. For instance, browsers switch to offline if a laptop lid is closed, or if a mobile phone screen is turned off. So continuing to connect is just a useless consumption of battery power.
This PR stops the reconnection loop and instead waits for the browser to switch to "online" again before resuming its reconnection attempts.
> Do not try to reconnect if the browser is offline

- src/protocols/websocket.js
- test/protocol/websocket.test.js
The `onerror` event handler called in browsers' WebSocket API differ from the one exposed by the `ws` module used in Node.js: the handler in browsers receive a generic `Event` object without any error information, while the ws handler receives a proper error.
Result: `kuzzle.connect().catch(e => console.log(e))` prints something like `Error: [object Event]` in a browser's console.
This PR fixes that issue by detecting the case and sending a generic `Connection error` to the connect promise handler.
Run the following script in a browser:
```html
<html>
<head>
<script src="node_modules/kuzzle-sdk/dist/kuzzle.js"></script>
</head>
<body>
<script>
const
// doesn't matter, must not reach any kuzzle server is what is important
ws = new KuzzleSDK.WebSocket('172.19.0.129', {port: 5555}),
kuzzle = …
```
> Fix erroneous error message on browser ws error

- .ci/doc/config.yml
- src/Kuzzle.js
- src/controllers/collection.js
- src/controllers/document.js
- src/controllers/index.js
- src/controllers/security/index.js
- test.js
- test.sh
- test/controllers/collection.test.js
- test/controllers/document.test.js
- test/controllers/index.test.js
- test/controllers/security.test.js
- test1.js
This PR fixes the way we pass the `refresh` option in several routes.
Before that, the option was lost and never passed to ES.
Ticket [Jira](https://jira.kaliop.net/projects/KZL/issues/KZL-1402?filter=allopenissues)
- Step 1 :
- Step 2 :
- Step 3 :  
...
> Fix option refresh in queries

- .ci/doc/config.yml
- codecov.yml
- package-lock.json
- package.json
- src/Kuzzle.js
- src/controllers/collection.js
- src/controllers/document.js
- src/controllers/index.js
- src/controllers/security/index.js
- src/protocols/abstract/realtime.js
- src/protocols/websocket.js
- test.js
- test.sh
- test/controllers/collection.test.js
- test/controllers/document.test.js
- test/controllers/security.test.js
- test/mocks/window.mock.js
- test/protocol/socketio.test.js
- test/protocol/websocket.test.js
- test1.js
- [ [#464](https://github.com/kuzzleio/sdk-javascript/pull/464) ] Fix option refresh in queries   ([Yoann-Abbes](https://github.com/Yoann-Abbes))
- [ [#463](https://github.com/kuzzleio/sdk-javascript/pull/463) ] Fix erroneous error message on browser ws error   ([scottinet](https://github.com/scottinet))
- [ [#455](https://github.com/kuzzleio/sdk-javascript/pull/455) ] Do not try to reconnect if the browser is offline   ([scottinet](https://github.com/scottinet))
---
> Release 7.0.0

- .travis.yml
Updates Travis condition to handle stable branches NPM.js deployments
> Handle multi stable branches NPM.js deployments

- src/controllers/document.js
- test/controllers/document.test.js
Fix a bug that prevent user of setting a `size` of `0` on `document.search`.
> Fix search with size=0

- .ci/test-docs.sh
- .travis.yml
- doc/7/controllers/security/create-or-replace-profile/snippets/create-or-replace-profile.js
- doc/7/controllers/security/create-or-replace-profile/snippets/create-or-replace-profile.test.yml
- doc/7/controllers/security/create-profile/snippets/create-profile.js
- doc/7/controllers/security/get-profile-rights/snippets/get-profile-rights.test.yml
- doc/7/controllers/security/get-profile/snippets/get-profile.test.yml
- doc/7/controllers/security/update-profile/snippets/update-profile.js
Adds a CI job only for the `master` branch, where the `deployments` section adds the `latest` tag to the published package. This way we have
* the `master` branch, published with the `latest` dist-tag
* the `*-stable` branches, published with no dist-tag
* the `*-beta` branches, published with the `beta` dist tag
Merge on `master` and ensure the next NPM release from the `master` branch has the `latest` tag.
* Fixed the tests that were failing because now Kuzzle V2 doesn't accept index and collection names containing uppercase letters.
* Added time to wait the dev server of the how-to
> [ci] Separate latest from stable deploy

- .ci/doc/docker-compose.yml
- .ci/docker-compose.yml
- doc/7/controllers/auth/create-api-key/index.md
- doc/7/controllers/auth/create-api-key/snippets/create-api-key.js
- doc/7/controllers/auth/create-api-key/snippets/create-api-key.test.yml
- doc/7/controllers/auth/delete-api-key/index.md
- doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.js
- doc/7/controllers/auth/delete-api-key/snippets/delete-api-key.test.yml
- doc/7/controllers/auth/search-api-keys/index.md
- doc/7/controllers/auth/search-api-keys/snippets/search-api-keys.js
- doc/7/controllers/auth/search-api-keys/snippets/search-api-keys.test.yml
- doc/7/controllers/security/create-api-key/index.md
- doc/7/controllers/security/create-api-key/snippets/create-api-key.js
- doc/7/controllers/security/create-api-key/snippets/create-api-key.test.yml
- doc/7/controllers/security/delete-api-key/index.md
- doc/7/controllers/security/delete-api-key/snippets/delete-api-key.js
- doc/7/controllers/security/delete-api-key/snippets/delete-api-key.test.yml
- doc/7/controllers/security/search-api-keys/index.md
- doc/7/controllers/security/search-api-keys/snippets/search-api-keys.js
- doc/7/controllers/security/search-api-keys/snippets/search-api-keys.test.yml
- features/steps/document.js
- src/Kuzzle.js
- src/controllers/auth.js
- src/controllers/security/index.js
- test/controllers/auth.test.js
- test/controllers/security.test.js
- test/kuzzle/query.test.js
Add the following methods:
- [security:createApiKey](https://deploy-preview-478--doc-sdk-javascript.netlify.com/controllers/security/create-api-key/)
- [security:deleteApiKey](https://deploy-preview-478--doc-sdk-javascript.netlify.com/controllers/security/delete-api-key/)
- [security:searchApiKeys](https://deploy-preview-478--doc-sdk-javascript.netlify.com/controllers/security/search-api-keys/)
- [auth:createApiKey](https://deploy-preview-478--doc-sdk-javascript.netlify.com/controllers/auth/create-api-key/)
- [auth:deleteApiKey](https://deploy-preview-478--doc-sdk-javascript.netlify.com/controllers/auth/delete-api-key/)
- [auth:searchApiKeys](https://deploy-preview-478--doc-sdk-javascript.netlify.com/controllers/auth/search-api-keys/)
- update docker-compose to use `elasticsearch:7` meta …
> Add API key methods

- doc/7/controllers/document/update/index.md
- src/controllers/document.js
- test/controllers/document.test.js
This PR adds a `source` option. Set to `true` returns the updated document in a `_source` object.
Depends to https://github.com/kuzzleio/kuzzle/pull/1549
Run Kuzzle within this branch https://github.com/kuzzleio/kuzzle/pull/1549
`document.update(index, collection, body, {source: true})`
> Add a "source" option for document:update to retrieve the updated document

- doc/7/getting-started/react-native/index.md
- doc/7/getting-started/react/with-redux/index.md
- doc/7/getting-started/vuejs/standalone/index.md
Fix links for getting started react, react native, vuejs for sdk JS 7.
Les liens vers `/core/2` ne seront pas accessible depuis le build netlify qui ne charge que les pages de doc du sdkl
Le test concernant les deadlink est pété d'ou le fail 
(ex: src/controllers/auth/login in src/sdk/js/7//getting-started/react-native/index.md)
ce lien fonctionne sur netlify
Netlify
/
Remove link to react kuzzle boilerplate in getting started react because it is not up to date with kuzzle versions
> Fix getting started links

- doc/7/controllers/document/search/index.md
- doc/7/core-classes/kuzzle-error/introduction/index.md
- doc/7/core-classes/search-result/next/index.md
- doc/7/essentials/error-handling/index.md
Adds information about scroll usage
> Add information about scroll

- .mocharc.json
- doc/7/core-classes/kuzzle-error/introduction/index.md
- doc/7/essentials/error-handling/index.md
- package-lock.json
- package.json
- src/Kuzzle.js
- src/controllers/document.js
- src/controllers/security/index.js
- src/protocols/http.js
- test/controllers/document.test.js
- test/mocha.opts
- test/protocol/http.test.js
The new `verb` HTTP specific option was handled by the SDK controllers, impacting all protocols, including WebSocket and MQTT
Impacted routes: `document:mGet` and `security:mGetUsers`
Those 2 routes send the `ids` argument to Kuzzle as a string, instead sending it as an array.
Fortunately, Kuzzle makes no difference between requests sent using HTTP or WebSocket or any other protocol, and it sanitizes the request in such a way that this bug is invisible to common users.
But documents aren't sanitized the same way when the API route is invoked by a plugin. And when that happens, the two routes mentioned earlier make any plugin invoking them crash.
This PR removes any specificities from the SDK controllers and, instead, makes the HTTP protocol handle the new `verb` option itself.
To do that, …
> Fix erroneous requests due to HTTP-specific settings 

- package-lock.json
- package.json
- src/controllers/document.js
- src/protocols/http.js
- test/controllers/document.test.js
- test/protocol/http.test.js
When we have multiple choose for a route, we choose the shortest or the GET route.  
With `document:create` we have the choice between those 2 routes:
```
{ verb: 'GET', url: '/:index/:collection/' },
{ verb: 'POST', url: '/:index/:collection/_search' }
```
The problem is that after even if we want to change the verb by using `options.verb`, the URL is not the good one and `GET /:index/:collection` correspond to the `collection:create` method.
So this PR is just a dirty fix to always use the POST route with `document:search`.  
When we are going to fully support the GET verb with query for `document:search`, maybe we can get ride of this.
See this failing job on Kuzzle: https://travis-ci.org/github/kuzzleio/kuzzle/jobs/667658863
> Hotfix document search http

- doc/7/controllers/collection/search-specifications/snippets/search-specifications.js
- doc/7/core-classes/search-result/next/snippets/scroll.js
- package-lock.json
- package.json
- src/Kuzzle.js
- test/controllers/document.test.js
- test/controllers/searchResult/document.test.js
- test/controllers/searchResult/profile.test.js
- test/controllers/searchResult/role.test.js
- test/controllers/searchResult/specifications.test.js
- test/controllers/searchResult/user.test.js
- test/controllers/security.test.js
- test/kuzzle/useController.test.js
Consider the following situation:
I have a custom controller in the package `custom-controller`:
- this package include `kuzzle-sdk` as peer dependencies
- this package expose a controller inheriting from `BaseController` class of `kuzzle-sdk`
I have my project including `custom-controller` and `kuzzle-sdk` as dependencies.
I will not be able to use my controller since the SDK checks if the controller is an instanceof `BaseController` but since these class are used in 2 different modules, the check fail.
This PR does not checks anymore if the controller is an instance of `BaseController` but it stills checks that the interface is respected (`kuzzle` and `name` properties present)
- use scroll of 10s
> Allow to use custom controller in another package

- src/controllers/Security.js
- src/core/searchResult/Profile.js
- src/core/security/Profile.js
- test/controllers/security.test.js
- test/core/security/profile.test.js
Profile contents returned by Kuzzle now have a `rateLimit` property which was missing from Profile objects returned by this SDK.
This PR adds that missing property to Profile objects.
* code wrap
* one var per const/let
> Add the rate limit property to Profile objects

- doc/7/controllers/security/refresh/index.md
- doc/7/controllers/security/refresh/snippets/refresh.js
- doc/7/controllers/security/refresh/snippets/refresh.test.yml
- src/controllers/Security.js
- test/controllers/security.test.js
Adds the `refresh` method of the security controller.
https://jira.kaliop.net/browse/KZL-1467
- Step 1 :
- Step 2 :
- Step 3 :  
...
> Add security:refresh

- src/controllers/Collection.js
- src/controllers/Document.js
- src/controllers/Security.js
- src/controllers/Server.js
- test/controllers/collection.test.js
- test/controllers/document.test.js
- test/controllers/security.test.js
- test/controllers/server.test.js
Before this PR we were mutating user options passed to SDK method (eg: `document:search`).  
It could lead to confusion because the user may want to reuse the same options object across different calls.
```bash
$ kourou collection:create index collection
```
This code should print `{ from: 0, size: 42 }` two times.
```js
const { Kuzzle, WebSocket } = require('./index')
const kuzzle = new Kuzzle(new WebSocket('localhost'));
(async () => {
const options = { from: 0, size: 42 }
console.log(options)
await kuzzle.document.search('index', 'collection', {}, options)
console.log(options)
kuzzle.disconnect();
})();
```
- remove custom errors when the result of `server:now` or `server:adminExists` is unexpected
> Avoid to mutate user options

- src/Kuzzle.js
- src/controllers/Auth.js
- src/controllers/Realtime.js
- src/protocols/abstract/Base.js
- test/controllers/auth.test.js
- test/controllers/realtime.test.js
- test/protocol/Base.test.js
Since we use the error code it's better to rely on the error `id` instead of the message.  
The error message when the token has expired has changed and so the corresponding event was not trigger anymore.
This PR fix this by using the error `id` instead.
```js
const {
Kuzzle,
Http
} = require('./index')
const kuzzle = new Kuzzle(new Http('localhost'))
kuzzle.on('networkError', console.error);
kuzzle.on('tokenExpired', () => {
console.log('Expired')
});
(async () => {
await kuzzle.connect()
await kuzzle.security.createUser('admin', {
content: { profileIds: [ 'default' ] },
credentials: { local: { username: 'admin', password: 'admin' } }
});
await kuzzle.auth.login('local', { username: 'admin', password: 'admin' }, '2s')
setTimeout(async () => {
try {
await kuzzle.server.now()
}
catch …
```
> Fix token expired

- .ci/doc/docker-compose.yml
- doc/7/controllers/document/search/index.md
- package-lock.json
- package.json
- src/controllers/Document.js
- src/protocols/Http.js
- src/protocols/WebSocket.js
- src/protocols/abstract/Base.js
- src/protocols/routes.json
- test/controllers/document.test.js
- test/protocol/Http.test.js
[Jira ticket](https://jira.kaliop.net/browse/KZL-1493)
This PR provides the possibility to execute a `document:search` with the GET http verb
Create a `nyc-open-data' index` and `yellow-taxi` collection.
Create some files with 2 containing field `{name:"ok"}`
Execute this code
Remove the `verb` option and/or change it to `POST` and re-execute the code
By default, `document:search` is still POST
```js
const { Kuzzle, Http } = require('kuzzle-sdk');
const kuzzle = new Kuzzle(
new Http(`localhost`, { port: 7512})
);
async function main () {
try {
const response = await kuzzle.document.search(
'nyc-open-data',
'yellow-taxi',
{
query:{
term: {
name: 'ok'
}
}
},{verb: 'GET'}
);
console.log(`Successfully get ${response.total} documents`);
} catch (error) { …
```
> Able to execute document search as GET http method

- doc/7/controllers/collection/update-mapping/index.md
- doc/7/controllers/collection/update/index.md
- doc/7/controllers/collection/update/snippets/update.js
- doc/7/controllers/collection/update/snippets/update.test.yml
- src/controllers/Collection.js
- src/protocols/routes.json
- test/controllers/collection.test.js
This PR adds `collection:update` to the sdk and deprecates the older `collection:updateMapping`.
Create an index/collection and update its mapping by calling the `collection:update` method
Tests
> Add collection:update and deprecate collection:updateMapping

- doc/7/controllers/bulk/delete-by-query/index.md
- doc/7/controllers/bulk/delete-by-query/snippets/delete-by-query.js
- doc/7/controllers/bulk/delete-by-query/snippets/delete-by-query.test.yml
- src/controllers/Bulk.js
- src/protocols/routes.json
- test/controllers/bulk.test.js
Add `bulk:deleteByQuery`
[Github Issue](https://github.com/kuzzleio/sdk-javascript/issues/521)
> Add bulk:deleteByQuery

- doc/7/controllers/security/m-get-profiles/snippets/m-get-profiles.test.yml
- doc/7/controllers/security/m-get-roles/snippets/m-get-roles.test.yml
- doc/7/controllers/security/m-get-users/snippets/m-get-users.test.yml
- src/controllers/Base.js
- src/controllers/MemoryStorage.js
- src/controllers/Realtime.js
- src/controllers/Security.js
- src/core/KuzzleEventEmitter.js
- src/core/Room.js
- src/core/searchResult/SearchResultBase.js
- src/core/security/Profile.js
- src/core/security/Role.js
- src/core/security/User.js
- test/controllers/realtime.test.js
- test/controllers/security.test.js
- test/core/room.test.js
Use `Reflect` to hide the kuzzle object from log
- Get ride of every `delete` keyword and use `Map` for RAM caches
- Do not throw custom error when unsubscribing from unknown room (let Kuzzle trigger it's own documented error)
- Allows to pass `_id` to `realtime.publish`
> Hide kuzzle object from console.log

- features/steps/document.js
- index.ts
- package.json
- src/controllers/Document.ts
- src/core/searchResult/Document.ts
- src/protocols/Http.js
- test/controllers/document.test.js
- test/core/searchResult/document.test.js
- test/protocol/Http.test.js
When using the HTTP protocol, URI parameters are sent as-is by the SDK, which leads to invalid URLs sent when parameters contain reserved or unicode characters.
* Encode URI keys and values when adding them in the URI
* Encode values when replacing URI placeholders
* Fix an incorrect module exports (e.g. "KuzzleEventEmitter" and other modules were exposed as subobjects)
* The `npm run test` script was outdated: it now uses the renamed npm scripts (i.e. test:* scripts)
* The `DocumentSearchResult` class was renamed `DocumentsSearchResult`, which _might_ be considered a breaking change (and is inconsistent with other *SearchResult object names anyway)
> Encode URI parameters when using the HTTTP protocol

- doc/7/controllers/collection/delete/index.md
- doc/7/controllers/collection/delete/snippets/delete-specifications.js
- doc/7/controllers/collection/delete/snippets/delete-specifications.test.yml
- src/controllers/Collection.js
- src/controllers/Index.js
- test/controllers/collection.test.js
This PR add the delete function and test for the Collection Controller
> Add support for the collection:delete API action

- doc/7/core-classes/kuzzle/constructor/index.md
- index.ts
- src/Kuzzle.ts
- src/core/KuzzleEventEmitter.ts
- src/protocols/Http.ts
- src/protocols/WebSocket.ts
- src/utils/interfaces.ts
Exports TS classes
- Step 1 : `npm run build && npm pack`
- Step 2 : Create a new project with `npm init` and add the `.tgz` file generated in the previous step as dependency
- Step 3 : Create a `test.ts` file and try to import the SDK from `kuzzle-sdk`
...
- add more types to `Kuzzle`
> Finalize typescript support

- src/KuzzleError.ts
- src/protocols/abstract/Base.ts
- test/protocol/Base.test.js
Keep the stacktrace from the client side instead of using Kuzzle's one
Before
```
NotFoundError: Controller action "valt" not found.
[...Kuzzle internal calls deleted...]
at Funnel.getController (/home/aschen/projets/kuzzleio/kuzzle/lib/api/funnel.js:582:28)
at Funnel.processRequest (/home/aschen/projets/kuzzleio/kuzzle/lib/api/funnel.js:400:29)
at /home/aschen/projets/kuzzleio/kuzzle/lib/api/funnel.js:282:23
```
After
```
KuzzleError: Controller action "valt" not found.
at WebSocketProtocol.query (/home/aschen/projets/kuzzleio/sdk-javascript/src/protocols/abstract/Base.ts:112:19)
at Proxy.query (/home/aschen/projets/kuzzleio/sdk-javascript/src/Kuzzle.ts:516:26)
🡆  at run (/home/aschen/projets/kuzzleio/sdk-javascript/test.js:10:30)
at processTicksAndRejections …
```
> Add meaningful stacktrace

- doc/7/controllers/bulk/import/index.md
Issue https://github.com/kuzzleio/sdk-javascript/issues/534
This PR fixes the 2 problems in the `bulk:import` documentation:
- Snippet display
- Missing function parameters
> Fix bulk:import documentation

- .travis.yml
- doc/7/controllers/security/search-roles/index.md
Remove "scroll" option from security:searchRoles doc
Change script test name for admin console tests
depends on https://github.com/kuzzleio/kuzzle-admin-console/pull/829
> Remove "scroll" option from security:searchRoles doc

- doc/7/getting-started/.react-native/package.json
- doc/7/getting-started/.react/with-redux/package.json
- doc/7/getting-started/.vuejs/package.json
- src/controllers/Realtime.ts
- test/controllers/realtime.test.js
Stick behavior of `realtime:unsubscribe` to documentation
Fix cypress tests by specifying `CYPRESS_RECORD_KEY_DOC` in `package.json` and Travis settings.
Since by default it uses `CYPRESS_RECORD_KEY`, it could not work since it's already used in the AC repo
> Stick `realtime:unsubscribe` behavior to documentation

- doc/7/getting-started/react-native/index.md
Add a disclaimer about Expo in getting started React Native
> [doc] Add a disclaimer about Expo in getting started React Native

- doc/7/controllers/collection/list/index.md
- doc/7/controllers/collection/update/index.md
- doc/7/controllers/security/search-api-keys/index.md
- doc/7/controllers/security/search-api-keys/snippets/search-api-keys.test.yml
- doc/7/getting-started/.react-native/package.json
- doc/7/getting-started/.react/with-redux/package.json
- doc/7/getting-started/.vuejs/package.json
- src/controllers/Security.js
- Grammar
- Fix `DeprecatedBadge` tags
Fix e2e tests like there: https://github.com/kuzzleio/sdk-javascript/pull/547
> Fix collection:list documentation

- .travis.yml
- package-lock.json
- package.json
- src/KuzzleError.ts
Remove the stacktrace enhancement. It's buggy and not accurate, we need another way to do that  but for now I'm just going to remove it
> Remove stacktrace enhancement

- src/types/Notification.ts
`Document` class was not imported for the `Notification` class so the default TS class was used
> Fix document notification result type

- src/types/ApiKey.ts
- src/types/Document.ts
- src/types/HttpRoutes.ts
- src/types/Mappings.ts
- src/types/ProfilePolicy.ts
- src/types/RoleRightsDefinition.ts
Allows to instantiate a `Document` without `_kuzzle_info`.
Fix the declaration of properties in `CollectionMappings`
> Fix types for Document and CollectionMappings

- src/protocols/Http.ts
- src/protocols/abstract/Base.ts
- test/protocol/Base.test.js
HTTP headers request field have a size limite: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431
When using the `document.mGet` method with the `get` verb, you can hit this limit who result in an 431 response with an empty body.
Now a specific error is trowed so developers can understand what is wrong
> Adds a specific error when the request is too big to use the GET verb 

- doc/7/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.js
- doc/7/controllers/realtime/subscribe/snippets/document-notifications.js
- doc/7/essentials/realtime-notifications/index.md
- src/types/Notification.ts
Add `event` property to document notifications
Related to https://github.com/kuzzleio/kuzzle/pull/1922
> Add event type to document notification

- doc/7/controllers/document/upsert/index.md
- doc/7/controllers/document/upsert/snippets/upsert.js
- doc/7/controllers/document/upsert/snippets/upsert.test.yml
- src/Kuzzle.ts
- src/controllers/Document.ts
- src/types/Document.ts
Add document:upsert API action (fix #572)
> Add document:upsert

- doc/7/controllers/auth/check-rights/index.md
- doc/7/controllers/auth/check-rights/snippets/check-rights.js
- doc/7/controllers/auth/check-rights/snippets/check-rights.test.yml
- doc/7/controllers/security/check-rights/index.md
- doc/7/controllers/security/check-rights/snippets/check-rights.js
- doc/7/controllers/security/check-rights/snippets/check-rights.test.yml
- src/controllers/Auth.ts
- src/controllers/Security.js
Add [auth|security]:checkRights https://github.com/kuzzleio/sdk-javascript/issues/571
- Step 1 :
- Step 2 :
- Step 3 :  
...
> Add [auth|security]:checkRights

- package-lock.json
- package.json
- src/types/Mappings.ts
Fix `MappingProperties` types
Launch Admin Console on `4-dev`
```
ERROR in /private/tmp/admin-console/node_modules/kuzzle-sdk-v7/src/types/Mappings.d.ts(8,5):
8:5 Property 'properties' of type 'MappingsProperties | undefined' is not assignable to string index type 'string | JSONObject'.
6 |      * @see https://docs.kuzzle.io/core/2/guides/main-concepts/data-storage/#mappings-properties
7 |      */
>  8 |     properties?: MappingsProperties;
|     ^
9 |     /**
10 |      * Dynamic mapping policy
11 |      *
ERROR in /private/tmp/admin-console/node_modules/kuzzle-sdk-v7/src/types/Mappings.d.ts(14,5):
14:5 Property 'dynamic' of type '"false" | "true" | "strict" | undefined' is not assignable to string index type 'string | JSONObject'.
12 |      * @see …
```
> [Hotfix] Fix type MappingProperties

- package-lock.json
- package.json
- src/controllers/Auth.ts
Fixes this [build error](https://app.netlify.com/sites/kuzzle-admin-console/deploys/60099111179c6800077bab7a) (seen on the Amin Console Netlify build). Webpack looks for a package called `src/types/RequestPayload` since the path doesn't start with `.`.
> [HOTFIX] relative import in Auth.ts

- doc/7/controllers/document/create-or-replace/index.md
- doc/7/controllers/document/create/index.md
- doc/7/controllers/document/delete-by-query/index.md
- doc/7/controllers/document/delete/index.md
- doc/7/controllers/document/m-create-or-replace/index.md
- doc/7/controllers/document/m-create/index.md
- doc/7/controllers/document/m-delete/index.md
- doc/7/controllers/document/m-replace/index.md
- doc/7/controllers/document/m-update/index.md
- doc/7/controllers/document/replace/index.md
- doc/7/controllers/document/update-by-query/index.md
- doc/7/controllers/document/update/index.md
- doc/7/controllers/document/upsert/index.md
- src/Kuzzle.ts
- src/controllers/Document.ts
- test/controllers/document.test.js
https://github.com/kuzzleio/kuzzle/pull/1946
> Allows to not send realtime notification on document controller

- src/KuzzleError.ts
- src/controllers/Auth.ts
- src/protocols/WebSocket.ts
- src/protocols/abstract/Base.ts
- src/utils/stackTrace.js
- test/protocol/Base.test.js
Improve SDK stacktrace by highlighting the user code and displaying Kuzzle stacktrace as well.
```
const { Kuzzle, Http, WebSocket } = require('./index');
const kuzzle = new Kuzzle(new WebSocket('localhost'));
function executeQuery () {
return kuzzle.query({
controller: 'greeting',
action: 'sayHello'
});
}
(async () => {
try {
await executeQuery();
}
catch (error) {
console.error(error)
}
finally {
kuzzle.disconnect();
}
})();
```
If Kuzzle is running in `development` mode then we display both stacktrace:
```
NotFoundError: API controller "greeting" not found.
[...Kuzzle internal calls deleted...]
at Funnel.getController (/var/app/node_modules/kuzzle/lib/api/funnel.js:595:24)
at Funnel.processRequest (/var/app/node_modules/kuzzle/lib/api/funnel.js:409:29)
at …
```
> Error stacktrace overhaul

- doc/7/essentials/events/index.md
- src/Kuzzle.ts
- src/protocols/WebSocket.ts
- src/protocols/abstract/Base.ts
- src/utils/clone.js
- test/kuzzle/connect.test.js
- test/kuzzle/protocol.test.js
- test/kuzzle/query.test.js
- test/protocol/WebSocket.test.js
When resubscribing after a `reconnected` event, the SDK use the original subscription `request` to re-subscribe.
The `Kuzzle.query` method mutate request and inject the JWT inside. Meaning that the request saved for the re-subscription already has a JWT inside.
This can be an issue because developers rely on the `kuzzle.jwt` property of the SDK to know if 1) the token is still valid 2) there are connection information.
Now the `request` and `options` parameter of the query method are cloned before modification.  (:warning: to save resources it's not a deep clone so only the top level properties are duplicated. Nested objects will not be cloned but only referenced)
Run a Kuzzle stack and then create this user and update anonymous role:
```
kourou security:createUser '{ …
```
> Fix re-subscription

- package-lock.json
- package.json
- src/protocols/WebSocket.ts
- src/protocols/abstract/Realtime.ts
- test/protocol/WebSocket.test.js
React Native WebSocket library throw an error when a message is sent through the socket while its state is still "CONNECTING".
Fix this issue by preventing send pings until its "OPEN"
> [HOTFIX] Check client readyState before sending pings

- package-lock.json
- package.json
- src/protocols/WebSocket.ts
- src/protocols/abstract/Realtime.ts
- test/protocol/WebSocket.test.js
Fixes the ping clearTimeout
- Step 1 :
- Step 2 :
- Step 3 :  
...
> [HOTFIX] Clear PingTimeout

- doc/7/controllers/security/create-user/snippets/create-user.test.yml
- doc/7/core-classes/user/properties/index.md
- src/core/security/User.ts
- test/core/security/user.test.js
Add a `_source` property containing the user custom content to match the API.
Fix #604
> Add _source property to user objects

- doc/7/controllers/security/get-user-strategies/index.md
- doc/7/controllers/security/get-user-strategies/snippets/get-user-strategies.js
- doc/7/controllers/security/get-user-strategies/snippets/get-user-strategies.test.yml
- src/controllers/Security.js
- src/protocols/routes.json
- test/controllers/security.test.js
As the title suggests, this **PR** implements the recently added [security:getUserStrategies](https://docs.kuzzle.io/core/2/api/controllers/security/get-user-strategies/) _(@ Kuzzle Backend)_
So it can be used directly, instead of having to use **query** to access it.
1. Create an example user and give it an auth strategy (ex. local).
2. Directly use `sdk.security.getUserStrategies(userKuid)`
3. Verify that you get a string array containing: `[ "local" ]` as response.
Closes #611
> Implement security:getUserStrategies

- doc/7/controllers/auth/login/index.md
- doc/7/controllers/auth/refresh-token/index.md
- doc/7/core-classes/kuzzle/constructor/index.md
- src/Kuzzle.ts
- src/controllers/Auth.ts
- src/protocols/Http.ts
- test/controllers/auth.test.js
This PR adds the option `cookieAuthentication` to enable the  support of cookie authentication in the SDK
along with some tests to ensure that everything is working properly.
Why making this an SDK option instead of a specific option for `auth:login`, `auth:checkToken`, `auth:refreshToken`, `auth:logout` ?
By making this a an option that can only be set at the initialization of the SDK we can avoid the user mixing cookie and token authentication at runtime, we can also throw at the initialization of the SDK if the feature is enabled when the SDK is not used in a browser
> Add cookie authentication support

- doc/7/core-classes/kuzzle/constructor/index.md
- src/Kuzzle.ts
- src/controllers/Base.ts
- src/types/ResponsePayload.ts
- src/utils/Deprecation.ts
- test/kuzzle/query.test.js
- test/utils/Deprecation.test.js
Closes #593
From now on, when developing with the SDK, you will see warning when using a deprecated action. You can disable this behavior by setting to false the deprecationWarning option on the kuzzle sdk object
Use a deprecated action and observe the warning(s)
Updated doc and added tests
> Print deprecation warning from Kuzzle

- doc/7/controllers/index/stats/index.md
- doc/7/controllers/index/stats/snippets/stats.js
- doc/7/controllers/index/stats/snippets/stats.test.yml
- src/controllers/Index.ts
- test/controllers/index.test.js
This **PR** implements the recently added [index:stats](https://docs.kuzzle.io/core/2/api/controllers/index/stats/) _(@ Kuzzle Backend v2.10.0)_
So it can be used directly, instead of having to use **query** to access it.
1. Launch a Kuzzle stack.
2. Directly use `sdk.index.stats()`
3. Verify that you get stats that make sense.
Closes #608 
> :information_source: It seems that **Codecov** is not taking the latest commit? :facepalm:
> Implement index:stats

- doc/7/core-classes/kuzzle-error/properties/index.md
- doc/7/essentials/error-handling/index.md
- src/KuzzleError.ts
Add the  `kuzzleStack` property containing the original stacktrace from Kuzzle.
It will allow to display only the Kuzzle stacktrace when an error occurs (e.g. in Kourou the user does not care about the SDK stacktrace)
> Add kuzzleStack property to KuzzleError

- .eslintignore
- .gitignore
- src/protocols/Http.ts
- test/protocol/Http.test.js
When Kuzzle exposes multiple HTTP routes for the same controller action, the SDK picks either the one with the shortest URL and, if there is a tie in URL lengths, it prefers the GET route to favor content caching.
But when multiple routes are available, all with the same size, and none are a GET route, the SDK picks... none of them. Resulting in some actions returning a "URL not found" when trying to use them.
This PR fixes that.
> Pick first route when multiple non-GET routes of the same size are available

- doc/7/core-classes/profile/serialize/index.md
- doc/7/core-classes/role/serialize/index.md
- doc/7/core-classes/user/serialize/index.md
- package-lock.json
- package.json
- src/controllers/Document.ts
- src/core/security/Profile.ts
- src/core/security/Role.ts
- src/core/security/User.ts
Since the last release, the user content is accessible under the `user._source` property in addition to the `user.content` property.
A getter was added for backward compatibility but when a User object was returned in a controller action it was serialized with only the `_source` property, breaking existing APIs relying on the `content` property.
This PR fix that but the sent data will be duplicated. A safe `serialize` method has been added to the User, Role and Profile classes and should be used instead of returning the instances directly.
> [HOTFIX] Ensure returning the user body in the content property when serialized

- .github/workflows/push_master.workflow.yml
Remove mentions of admin-console-tests in workflow. Indeed those tests were commented in another [PR](https://github.com/kuzzleio/sdk-javascript/pull/625) and CI fails because of that.
> Remove mentions of admin console tests in workflow

- doc/7/getting-started/.react/with-redux/src/App.js
Change in documentation: using `messages.indexOf(message)` is not necessary to get index because we can get it from callback 2nd argument
> docs: use index from callback argument instead of indexOf

- doc/7/core-classes/kuzzle/constructor/index.md
- package-lock.json
- package.json
- src/protocols/WebSocket.ts
- test/protocol/WebSocket.test.js
This PR change the behaviour of the websocket's `connect` method to call `HttpProtocol.connect()` if the support of cookieAuthentication is enabled.
Without that the HttpProtocol routes are not constructed, causing it to not send the payloads.
```bash
npm run test
```
Correction of a wrong statement in the cookieAuth option of the Kuzzle constructor.
> Fix cookie authentication support for WebSocket

- doc/7/controllers/document/delete-fields/index.md
- doc/7/controllers/document/delete-fields/snippets/deleteFields.js
- doc/7/controllers/document/delete-fields/snippets/deleteFields.test.yml
- src/controllers/Document.ts
- test/controllers/document.test.js
This PR add the action `document:deleteFields` and the associated documentation and tests
⚠️ Depends on #632
> Add support for the document:deleteFields API action

- doc/7/essentials/events/index.md
- src/Kuzzle.ts
- src/protocols/DisconnectionOrigin.ts
- src/protocols/WebSocket.ts
- src/protocols/abstract/Realtime.ts
- test/mocks/protocol.mock.js
- test/protocol/WebSocket.test.js
This PR adds an `origin` parameter to the Kuzzle disconnected event.
This parameter describes what is causing the disconnected event.
**Origins**
| Name                     | Description                                                                                                                                                        |
| ------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `websocket/auth-renewal` | The websocket protocol si reconnecting to renew the token. See [Websocket Cookie Authentication](sdk/js/7/protocols/websocket/introduction#cookie-authentication). |
| `user/connection-closed` | The disconnection is done by the user. …
> Add an origin parameter to the kuzzle disconnected event

- doc/7/controllers/bulk/update-by-query/index.md
- doc/7/controllers/bulk/update-by-query/snippets/update-by-query.js
- doc/7/controllers/bulk/update-by-query/snippets/update-by-query.test.yml
- doc/7/controllers/document/m-upsert/index.md
- doc/7/controllers/document/m-upsert/snippets/m-upsert.js
- doc/7/controllers/document/m-upsert/snippets/m-upsert.test.yml
- src/controllers/Bulk.ts
- src/controllers/Document.ts
- src/protocols/routes.json
Add `bulk:updateByQuery` and `document:mUpsert` api actions
> Add bulk:updateByQuery and document:mUpsert

- .eslintignore
- .gitignore
- src/Kuzzle.ts
- test/kuzzle/queue.test.js
When requests are queued, there are 2 constructor options that can lead to abort them before they can be sent to Kuzzle:
* queueTTL: if set to a value larger than 0, queued requests can expire
* queueMaxSize: if set to a value larger than 0, the queue has a maximum number of requests it can hold. If reached, older requests are aborted to make place for newer ones
When requests are aborted because of those configurations, an `offlineQueuePop` event is emitted, but:
* the invalid argument is provided, making the event deliver an `undefined` payload
* the promise associated to the aborted request is not rejected, making clients await indefinitely for them
This PR fixes these issues, and add the missing unit tests that should have caught these problems earlier.
* the `offlineQueuePop` event …
> Correctly reject aborted queued requests

- doc/7/core-classes/kuzzle/constructor/index.md
- doc/7/essentials/offline-tools/index.md
The `queueTTL` option documentation is missing a crucial piece of information: when set to 0, queued requests never expire.
> doc: missing behavior documentation when setting queueTTL to 0

- .github/actions/dead-links/action.yml
- .github/actions/doc-deploy/action.yml
- .github/workflows/push_master.workflow.yml
Following the latest improvements in the Docs CI workflow, we need to have isomorphic dependencies (thus `npm ci`) but the latest Kuzdoc minor within the major specified by `package.json` (thus `npm i kuzdoc`). Having the latest minor of Kuzdoc enables us to easily deploy non-breaking changes to all the CIs without manually bump the Kuzdoc dependency (which would be the case if we just`npm ci`).
Also, this PR re-activates the dead-link check, using the SSH-key.
Sorry for the linting.
⚠️  Once merged, we should merge back to `7-dev`
> Latest kuzdoc minor and dead-link check

- src/core/searchResult/SearchResultBase.ts
- test/core/searchResult/document.test.js
- test/core/searchResult/profile.test.js
- test/core/searchResult/specifications.test.js
- test/core/searchResult/user.test.js
When using the `SearchResult.next` method with HTTP, the route was used with the `search` options, including the use of the `POST` verb. 
This leads to use a different API action (`collection:update`) since the `document:scroll` API action only exists with the `GET` verb
> Fix usage of SearchResult.next with HTTP

- src/core/Jwt.js
- test/core/Jwt.test.js
- test/mocks/generateJwt.mock.js
…ison (between timestamp in ms and sec)
Issue #647
> Fix the Jwt.expired getter wrong comparison of micro timestamp and timestamp

- src/protocols/WebSocket.ts
- test/protocol/WebSocket.test.js
This PR fixes a Race Condition that was occuring within the Heartbeat causing the SDK to think the connection was lost and making him engage the reconnection protocol which was causing the SDK to create multiple Websocket connection even though the previous connections were fine.
This is a serious problem that could cause applications to be overloaded with Websocket connections and can saturate the Event Loop or the limit of Websocket connections defined by the browsers.
What has been done:
- Avoid creating a Timeout in the the ping Interval since they had the same amount of time before execution and that caused  a race condition, we now only have an Interval that checks if there has been a pong since the last cycle, if not throw an Error, if there was a pong since the last ping cycle do …
> Hotfix heartbeat race condition

- doc/7/core-classes/kuzzle/authenticate/index.md
- doc/7/core-classes/kuzzle/authenticate/snippets/authenticate.js
- doc/7/core-classes/kuzzle/authenticate/snippets/authenticate.test.yml
- doc/7/core-classes/kuzzle/properties/index.md
- doc/7/essentials/offline-tools/index.md
- src/Kuzzle.ts
- src/protocols/WebSocket.ts
- test/kuzzle/authenticator.test.js
- test/kuzzle/listenersManagement.test.js
When the SDK reconnect to Kuzzle, it trigger the `reconnected` event. The Realtime controller will try to resubscribe when this event is triggered.
If the token had expired, then the Realtime controller will try to resubscribe with no authentication and thus the subscriptions request may fail.
This PR include a new `authenticator` property, this property should contain a function that authenticate the SDK (with `auth.login` for example).  
The SDK will call the function before emitting the reconnected event, if the SDK was authenticated and cannot re-authenticate then the `reconnected` event will not be emitted and the SDK will be in the `disconnected` state.
A new `reconnectionError` has been added and is triggered when the reconnection has failed
Create an user:
```
kourou …
```
> Add authenticator function used at reconnection

- .ci/test-docs.sh
- doc/7/getting-started/.vuejs/package-lock.json
- doc/7/getting-started/.vuejs/package.json
- package-lock.json
- src/Kuzzle.ts
- src/controllers/Auth.ts
- src/controllers/Realtime.ts
- src/protocols/WebSocket.ts
- src/protocols/abstract/Realtime.ts
- test/kuzzle/authenticator.test.js
- test/kuzzle/listenersManagement.test.js
- test/protocol/WebSocket.test.js
When the SDK subscribe to realtime notification and the authentication expire, Kuzzle send a `TokenExpired` notification.  
When the SDK receive this notification, it unsubscribe from every realtime subscriptions.
A proper re-authentification mechanism should be implemented instead when the `authenticator` property has been set
> Reconnect with authenticator when receiving TokenExpired event

- src/Kuzzle.ts
- test/kuzzle/authenticator.test.js
- test/kuzzle/protocol.test.js
This PR enables the automatic resubscription of the SDK when logged in using the JWT property
> Automatic resubscription when logged in using jwt property

- src/controllers/Realtime.ts
This PR make a slight changes in the way we loop over the `Map.keys()` in the `saveSubscription`, `resubscribe` and `removeSubscriptions` method, because Webpack is incorrectly transpiling the loops making those methods not working properly.
Instead of iterating this way
```js
for (const roomId of this._subscriptions.keys()) {
// Body
}
```
The iteration is now done using `Map.forEeach`
```js
this._subscriptions.forEach((rooms, roomId) => {
// Body
});
```
Like I said, those changes are made to fix an issue where the resubscription mecanism wasn't working in the JS SDK but only in the browser.
This was caused by a bad transpilation of the loops using Webpack:
```js
for (const roomId of this._subscriptions.keys())
```
That were transpiled to:
```js
for(let …
```
> Resubscription not working in the browser because of a bad transpilation

- doc/7/protocols/http/constructor/index.md
- doc/7/protocols/http/constructor/snippets/constructor.js
- src/protocols/Http.ts
- test/protocol/Http.test.js
This PR allows to define custom HTTP headers that will be send with every request made by the SDK.
Those headers are defined when instantiating the HTTP protocol:
```js
const kuzzle = new Kuzzle(new Http('localhost', { 
headers: {
'Accept-Encoding': 'gzip, deflate'
}
}));
```
For example, this allows to use a different `Accept-Encoding` header to use gzip or deflate compression with Kuzzle
> Allows to define custom headers for HTTP protocol

- doc/7/controllers/document/upsert/index.md
- src/controllers/Document.ts
- test/controllers/document.test.js
The `options.default` option of `document.upsert` method was wrong: instead of `default`, the `defaults` property was sent to Kuzzle
> Fix upsert options.default 

- src/Kuzzle.ts
- test/kuzzle/authenticator.test.js
Emit a reconnectionError when there is no authenticator set.
> Fix reconnectionError not emittend when authenticator is missing

- doc/7/core-classes/kuzzle-error/properties/index.md
- src/KuzzleError.ts
- src/protocols/abstract/Base.ts
- test/protocol/Base.test.js
⚠️ Depends on #619 
This PR adds more context from the Kuzzle error response to the error objects (**KuzzleError**): ```controller, action, volatile, index, collection```
New error output example:
```
NotFoundError: API action "foo":"bar" not found
|
|
Status: 404
Controller: foo
Action: bar
KuzzleAbstractProtocol
|
|
at KuzzleAbstractProtocol.query (/Users/clementbolin/Epitech/Kuzzle/sdk-javascript/src/protocols/abstract/Base.ts:37:6)
>    at Context.<anonymous> (/Users/clementbolin/Epitech/Kuzzle/sdk-javascript/test/protocol/Base.test.js:215:23)
at callFn (/Users/clementbolin/Epitech/Kuzzle/sdk-javascript/node_modules/mocha/lib/runnable.js:366:21)
at Test.Runnable.run (/Users/clementbolin/Epitech/Kuzzle/sdk-javascript/node_modules/mocha/lib/runnable.js:354:5)
...
```
```npm run …
```
> Add more context to errors

- doc/7/core-classes/kuzzle/properties/index.md
- doc/7/essentials/events/index.md
- src/Kuzzle.ts
- src/controllers/Document.ts
- src/types/index.ts
- src/types/mRequests.ts
- src/types/mResponses.ts
- test/kuzzle/listenersManagement.test.js
Add specifics types for `m*` methods.
- ensure `authenticated` is always a boolean
- add missing documentation
- expose events in the Kuzzle object
> Add types for mRequests and mResponses

- package-lock.json
- package.json
- src/KuzzleError.ts
`MultipleErrorsError` includes the detailed list of errors returned by Kuzzle in the `errors` property but it was not correctly handled by the SDK
> Release 7.8.2: Fix multiple errors error

- doc/7/essentials/debugging/index.md
- src/Kuzzle.ts
- src/controllers/Auth.ts
- src/utils/Deprecation.ts
- src/utils/debug.js
Adds a debug mode for the SDK that prints every requests and responses.
To activate in Node.js: `export DEBUG=kuzzle-sdk`
To activate in the Browser: add the following search param in the URL `?debugKuzzleSdk`
> Add debug mode

- doc/7/core-classes/base-controller/introduction/index.md
- doc/7/core-classes/base-controller/properties/index.md
- doc/7/core-classes/base-controller/query/index.md
- doc/7/essentials/batch-processing/index.md
- doc/7/essentials/strong-typing/index.md
- package-lock.json
- package.json
- src/types/KDocument.ts
Make document metadata optional in KDocumentContent so users can instantiate their own document content without having to fill the `_kuzzle_info` field.
- add missing sincebadge
> Make document metadata optional in KDocumentContent

- index.ts
- src/Kuzzle.ts
- src/controllers/Server.ts
- test/controllers/server.test.js
add the following action `server:capabilities`
with unit tests: `npm run test:unit`
or with a Kuzzle app:
```ts
import { Backend } from 'kuzzle'
const app = new Backend('app-sample')
app.start()
.then(() => {
app.log.info('Application started')
app.sdk.server.capabilities()
})
.catch(console.error)
```
export Server controller
> Add `server:capabilities` method

- src/controllers/Document.ts
Add strong types for `updateByQuery` and `upsert`
> Add missing strong types in document controller

- doc/7/core-classes/kuzzle-error/properties/index.md
- src/KuzzleError.ts
- src/protocols/abstract/Base.ts
Kuzzle returns a `props` property with error, this property contains all the string used to build the error message.
Those string can be used by the application layer to build other error messages.
This PR expose this property
> Add `props` in KuzzleError

- doc/7/essentials/events/index.md
- src/Kuzzle.ts
- src/core/Room.js
- test/core/room.test.js
- test/kuzzle/listenersManagement.test.js
#682 
Add event at callback error in subscription.
An new event type has been created.
Considering `index1:collection1` exist, this code:
```js
const {
Kuzzle,
WebSocket,
} = require('kuzzle-sdk');
const kuzzle = new Kuzzle(
new WebSocket('localhost')
);
kuzzle.on('networkError', error => {
console.error('Network Error:', error);
});
const run = async () => {
try {
console.log('--- Subscribe to event');
kuzzle.on(
'callbackError',
(error) => console.log(
`Error message "${error.error.message}" on "${error.room.index}:${error.room.collection}"`)
);
const cb = () => {throw new Error("I am a callback and I threw an error")};
const fieldA = 'callbackErrorTest';
const filter = {
equals: {
fieldA
}
};
console.log('--- Subscribe with callback');
await …
```
> Add event at callback error in subscription

- .github/actions/tests-ac/action.yml
- doc/7/controllers/security/get-user-mapping/snippets/get-user-mapping.test.yml
- doc/7/controllers/security/search-users/snippets/search-users-es.test.yml
- doc/7/controllers/security/search-users/snippets/search-users-koncorde.test.yml
- src/types/Mappings.ts
Fix the `MappingsProperties` type to reflect the real mappings object structure
> Fix the `MappingsProperties` type

- .github/actions/tests-ac/action.yml
- doc/7/controllers/security/get-user-mapping/snippets/get-user-mapping.test.yml
- doc/7/controllers/security/search-users/snippets/search-users-es.test.yml
- doc/7/controllers/security/search-users/snippets/search-users-koncorde.test.yml
- doc/7/essentials/debugging/index.md
- src/utils/debug.js
Allows to set the `window.debugKuzzleSdk` variable to `true` to activate debug mode from the browser.
- avoid multiple calls to `process.env`
- print directly the object in the browser
> Add support for debug in browser from window object

- src/core/searchResult/SearchResultBase.ts
- src/protocols/abstract/Realtime.ts
- test/core/searchResult/document.test.js
- test/core/searchResult/profile.test.js
- test/core/searchResult/role.test.js
- test/core/searchResult/specifications.test.js
- test/core/searchResult/user.test.js
Fix bug where calling next on search with a from always return the same results
Prior to this change the SDK was always returning the same result each time the `next()` was called because the search was overriding the incremented `from` property with the given `from` property in the options causing each call to `next` to do a search from the begining
```js
const KuzzleSDK = require('kuzzle-sdk');
const kuzzle = new KuzzleSDK.Kuzzle(
new KuzzleSDK.WebSocket(kuzzleHost),
);
(async () => {
let results = await kuzzle.document.search('test','test',{},{from: 1, size:1}); 
while (results) {
console.log('res', results.hits.map(r=>r._id))
results = await results.next();
}
})();
```
> Fix bug where calling next on search with a from always return the same results

- src/controllers/Document.ts
As mentioned in #700 , the `refresh` option type was not well defined in this section. This as been fixed by @Aschen in the past month but when checking the code before closing the issue, I noticed there were still two action of the `document` controller that still have a wrongly defined type for this field. In order to close #700, this PR aim to update these
> Allow to use `refresh: false` with `document:upsert|deleteByQuery`

- src/utils/debug.js
Fixes an edge case happening with react-native.
Frameworks like react-native sometimes emulate the `window` object when running outside of the browser,
this causes an edge case where the `window` object exists but `window.location` doesn't since there is no pages in an iOS / Android application for example.
This caused our debug utility to call `new URL` on an undefined value throwing an error, 
This was preventing the usage of the SDK with react-native like in the issue #703.
> Fix error with React Native

- src/protocols/Http.ts
- test/protocol/Http.test.js
Intend to fix #713 by adding a edge case handling in the request [payload forging loop](https://github.com/kuzzleio/sdk-javascript/blob/6aaf6e1630187a885191fd57123b7b25d946fb40/src/protocols/Http.ts#L264-L283) that allow user to call a custom HTTP GET route that expects to receive queries named index and/or collection.
> Allow to call custom GET HTTP method with index and collection args

- index.ts
- src/protocols/abstract/Realtime.ts
- src/utils/browser.ts
- src/utils/debug.js
- test/mocks/window.mock.js
Add an helper that adds safer methods to obtain the `window` scope and to check if we are running inside of a browser.
> Add a safer check to know if we are inside of a browser

- package-lock.json
- package.json
- src/Kuzzle.ts
Allows to specify only the request type without the result
```
await sdk.query<ApiDeviceLinkAssetRequest>({ ... });
```
> Allows to specify only request type in query

- doc/7/controllers/auth/create-api-key/snippets/create-api-key.js
- src/Kuzzle.ts
Simplify the API by adding a helper function to set the JWT only with kuzzle API key format.
ping @Aschen 
It looks like it's only used by API Token and this way this has more domain correlation between both. Users shouldn't have to set the JWT on their own generally. This is abstraction of the SDK
> Add support and documentation to use API keys

- src/Kuzzle.ts
- src/core/KuzzleEventEmitter.ts
- src/protocols/DisconnectionOrigin.ts
- src/protocols/WebSocket.ts
- src/protocols/abstract/Realtime.ts
- src/types/JSONObject.ts
- src/types/Notification.ts
- test/kuzzle-sdk-test.ts
- test/protocol/WebSocket.test.js
- tsconfig.json
Hi[^contact],
[^contact]: You can contact me on Discord if you have any questions and expect a quick answer. I'm already listed as a Contributor on it 😅.
Working on a new project with Kuzzle, I'm fixing some code to improve user experience.
**ℹ️ Note:** I'll keep updating this PR whenever I add new types (probably some in the following weeks).
Improved the Notification type for real-time notification in order to work with type inference.
<details>
<summary>Read details</summary>
```ts
kuzzle.realtime.subscribe("index", "messages", {}, (notification) => {
// Only notification.type available
if (notification.type === "document") {
// notification still has no more properties…
}
});
```
Before `notification` only contains the `type` property which is good because at this step we don't know …
> Improve typings

- doc/7/controllers/auth/create-api-key/snippets/create-api-key.js
- package-lock.json
- package.json
- src/Kuzzle.ts
- src/core/KuzzleEventEmitter.ts
- src/protocols/DisconnectionOrigin.ts
- src/protocols/WebSocket.ts
- src/protocols/abstract/Realtime.ts
- src/types/JSONObject.ts
- src/types/Notification.ts
- test/kuzzle-sdk-test.ts
- test/protocol/WebSocket.test.js
- tsconfig.json
- [ [#723](https://github.com/kuzzleio/sdk-javascript/pull/723) ] Improve typings   ([ScreamZ](https://github.com/ScreamZ))
- [ [#724](https://github.com/kuzzleio/sdk-javascript/pull/724) ] Add support and documentation to use API keys   ([ScreamZ](https://github.com/ScreamZ))
---
> Release 7.10.7

- src/types/KDocument.ts
It adds `index` and `collection` to `KHit<>`.
Those fields are necessary for the multi-search results.
> Add index and collection fields to KHit

- .github/actions/es-lint/action.yml
- .github/actions/functional-tests/action.yml
- .github/actions/snippet-tests/action.yml
- .github/actions/unit-tests/action.yml
- src/protocols/Http.ts
- test/protocol/Http.test.js
Prevent passing empty strings into JSON.parse when using raw responses over HTTP.
> Fix empty raw responses parsed as json

- src/types/ProfilePolicy.ts
Fix ProfilePolicy.ts, restrictedTo is an array of restrictions
> fix: (ProfilePolicy.ts) restrictedTo was mistyped

- .ci/doc/config.yml
- .ci/doc/docker-compose.yml
- .ci/doc/eslint.json
- .github/workflows/pull_request.workflow.yml
- doc/7/essentials/offline-tools/index.md
- src/Kuzzle.ts
Reapply current JWT before executing offlineQueue requests.
Since the final user could use the authenticator with a short JWT TTL or being disconnected for a big amount of time from his Kuzzle backend.
> Reapply current JWT before executing offlineQueue requests

- .ci/start_kuzzle.sh
- .ci/test-docs.sh
- doc/7/essentials/events/index.md
- src/Kuzzle.ts
- src/controllers/Auth.ts
- src/core/KuzzleEventEmitter.ts
- test/controllers/auth.test.js
- test/kuzzle/authenticator.test.js
- test/kuzzle/listenersManagement.test.js
Add **before** and **after** events for login and logout events to replace `loginAttempt` and `logoutAttempt` (previous events are keep for legacy).
So add the follow events:
- `beforeLogin` triggered before login attempt
- `afterLogin` triggered after login attempt and work exactly same as `loginAttempt` (same callback arguments)
- `beforeLogout` triggered before logout attempt
- `afterLogout` triggered after logout attempt and work exactly same as `logoutAttempt` (same callback arguments)
- Refactor logout method to handle error and trigger `afterLogout` and `logoutAttempt` in error case
- Add logout events documentation
KZLPRD-492
> feat(auth): improve auth events

- src/types/Notification.ts
Improve document payload according to real documentation
https://docs.kuzzle.io/core/2/api/payloads/notifications/#document-notification
Can you ping me on release @rolljee  @etrousset ? Thanks :)
> Update Notification interface to match correct API

- src/controllers/Document.ts
It allows to export UpdateByQueryResponse interface
- Step 1 :
- Step 2 :
- Step 3 :
> feat: create an interface to export and use in KDM

- .github/workflows/pull_request.workflow.yml
- .github/workflows/push_branches.workflow.yaml
Update workflows with runner ubuntu 24.04
> chore(workflow): update ubuntu runner

- .github/workflows/pull_request.workflow.yml
- .github/workflows/push_branches.workflow.yaml
- CHANGELOG.md
- package-lock.json
- package.json
- src/types/mResponses.ts
Update workflow ubuntu worker to 24.04
> fix(workflow): upgrade to ubuntu 24.04
